import type { ComplianceMetrics, STIGFinding } from '@/hooks/useSTIGCompliance';

export const DEMO_ORG_ID = 'demo-acme-defense-corp';
export const DEMO_ORG_NAME = 'ACME Defense Corp';

export const DEMO_METRICS: ComplianceMetrics = {
  total_assets: 12,
  compliant_assets: 9,
  non_compliant_assets: 3,
  overall_compliance_percentage: 74,
  critical_findings: 3,
  high_findings: 8,
  medium_findings: 11,
  recent_scans: 4,
  automated_remediations: 6,
};

export const DEMO_FINDINGS: STIGFinding[] = [
  {
    id: 'demo-f-001',
    scan_id: 'demo-scan-001',
    asset_id: 'demo-asset-rhel-01',
    rule_id: 'RHEL-08-010010',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_I',
    finding_details: {
      title: 'RHEL 8 must lock accounts after 3 consecutive invalid logon attempts',
      fix_text: 'Configure the operating system to lock an account after three consecutive invalid logon attempts using pam_faillock.',
      check_content: 'Verify pam_faillock.so is configured in /etc/pam.d/system-auth.',
      vuln_id: 'V-230333',
    },
    evidence: [],
    remediation_status: 'pending',
    remediation_priority: 1,
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-05-01T14:22:00Z',
    environment_assets: { asset_name: 'sentinel-gateway-01', platform: 'aws', operating_system: 'RHEL 8.9' },
  },
  {
    id: 'demo-f-002',
    scan_id: 'demo-scan-001',
    asset_id: 'demo-asset-win-01',
    rule_id: 'WN10-CC-000038',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_I',
    finding_details: {
      title: 'The Windows SMBv1 protocol must be disabled on the SMB server',
      fix_text: 'Disable SMBv1 via PowerShell: Set-SmbServerConfiguration -EnableSMB1Protocol $false -Force',
      check_content: 'Verify Get-SmbServerConfiguration | Select EnableSMB1Protocol returns False.',
      vuln_id: 'V-220706',
    },
    evidence: [],
    remediation_status: 'in_progress',
    remediation_priority: 1,
    created_at: '2026-04-16T09:00:00Z',
    updated_at: '2026-05-02T11:00:00Z',
    environment_assets: { asset_name: 'dc-workstation-14', platform: 'onprem', operating_system: 'Windows 10 22H2' },
  },
  {
    id: 'demo-f-003',
    scan_id: 'demo-scan-002',
    asset_id: 'demo-asset-rhel-01',
    rule_id: 'RHEL-08-010020',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_I',
    finding_details: {
      title: 'RHEL 8 must enforce password complexity by requiring at least one uppercase character',
      fix_text: 'Edit /etc/security/pwquality.conf and set ucredit = -1.',
      check_content: 'grep -i ucredit /etc/security/pwquality.conf',
      vuln_id: 'V-230361',
    },
    evidence: [],
    remediation_status: 'pending',
    remediation_priority: 1,
    created_at: '2026-04-16T09:15:00Z',
    updated_at: '2026-05-02T11:10:00Z',
    environment_assets: { asset_name: 'sentinel-gateway-01', platform: 'aws', operating_system: 'RHEL 8.9' },
  },
  {
    id: 'demo-f-004',
    scan_id: 'demo-scan-001',
    asset_id: 'demo-asset-rhel-02',
    rule_id: 'RHEL-08-020030',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_II',
    finding_details: {
      title: 'RHEL 8 must not allow accounts configured with blank or null passwords',
      fix_text: 'Edit /etc/pam.d/system-auth and remove nullok from the pam_unix.so line.',
      check_content: 'grep nullok /etc/pam.d/system-auth',
      vuln_id: 'V-230380',
    },
    evidence: [],
    remediation_status: 'pending',
    remediation_priority: 2,
    created_at: '2026-04-17T08:00:00Z',
    updated_at: '2026-04-30T16:00:00Z',
    environment_assets: { asset_name: 'api-server-prod-02', platform: 'aws', operating_system: 'RHEL 8.9' },
  },
  {
    id: 'demo-f-005',
    scan_id: 'demo-scan-002',
    asset_id: 'demo-asset-win-01',
    rule_id: 'WN10-AU-000500',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_II',
    finding_details: {
      title: 'Windows 10 must be configured to audit Other Policy Change Events Successes',
      fix_text: 'Configure the policy: Computer Configuration >> Windows Settings >> Security Settings >> Advanced Audit Policy Configuration.',
      check_content: 'auditpol /get /subcategory:"Other Policy Change Events"',
      vuln_id: 'V-220776',
    },
    evidence: [],
    remediation_status: 'pending',
    remediation_priority: 2,
    created_at: '2026-04-18T10:00:00Z',
    updated_at: '2026-05-01T09:00:00Z',
    environment_assets: { asset_name: 'dc-workstation-14', platform: 'onprem', operating_system: 'Windows 10 22H2' },
  },
  {
    id: 'demo-f-006',
    scan_id: 'demo-scan-002',
    asset_id: 'demo-asset-rhel-02',
    rule_id: 'RHEL-08-030010',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_II',
    finding_details: {
      title: 'RHEL 8 must enable Linux audit logging for the SSH daemon',
      fix_text: 'Add "audit yes" to /etc/ssh/sshd_config and restart sshd.',
      check_content: 'grep -i "^audit" /etc/ssh/sshd_config',
      vuln_id: 'V-230301',
    },
    evidence: [],
    remediation_status: 'in_progress',
    remediation_priority: 2,
    created_at: '2026-04-19T12:00:00Z',
    updated_at: '2026-05-03T08:00:00Z',
    environment_assets: { asset_name: 'api-server-prod-02', platform: 'aws', operating_system: 'RHEL 8.9' },
  },
  {
    id: 'demo-f-007',
    scan_id: 'demo-scan-003',
    asset_id: 'demo-asset-win-02',
    rule_id: 'V-225012',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_II',
    finding_details: {
      title: 'Windows Server must use FIPS 140-2 approved encryption algorithms',
      fix_text: 'Enable FIPS policy: Computer Configuration >> Windows Settings >> Security Settings >> Local Policies >> Security Options.',
      check_content: 'Verify the FIPS algorithm policy setting is Enabled.',
      vuln_id: 'V-225012',
    },
    evidence: [],
    remediation_status: 'pending',
    remediation_priority: 2,
    created_at: '2026-04-20T11:00:00Z',
    updated_at: '2026-05-01T14:00:00Z',
    environment_assets: { asset_name: 'dc-server-prod-01', platform: 'onprem', operating_system: 'Windows Server 2022' },
  },
  {
    id: 'demo-f-008',
    scan_id: 'demo-scan-001',
    asset_id: 'demo-asset-rhel-01',
    rule_id: 'RHEL-08-040010',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_III',
    finding_details: {
      title: 'RHEL 8 must be configured to use the shadow file to store only encrypted representations of passwords',
      fix_text: 'Set the crypt_style in /etc/libuser.conf and run pwconv.',
      check_content: 'grep -i crypt_style /etc/libuser.conf',
      vuln_id: 'V-230498',
    },
    evidence: [],
    remediation_status: 'pending',
    remediation_priority: 3,
    created_at: '2026-04-21T09:00:00Z',
    updated_at: '2026-04-29T15:00:00Z',
    environment_assets: { asset_name: 'sentinel-gateway-01', platform: 'aws', operating_system: 'RHEL 8.9' },
  },
  {
    id: 'demo-f-009',
    scan_id: 'demo-scan-003',
    asset_id: 'demo-asset-win-02',
    rule_id: 'WN22-CC-000050',
    organization_id: DEMO_ORG_ID,
    finding_status: 'Open',
    severity: 'CAT_III',
    finding_details: {
      title: 'Windows Server 2022 must have WDigest Authentication disabled',
      fix_text: 'Set HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest UseLogonCredential to 0.',
      check_content: 'Verify reg key UseLogonCredential is 0 or does not exist.',
      vuln_id: 'V-254261',
    },
    evidence: [],
    remediation_status: 'pending',
    remediation_priority: 3,
    created_at: '2026-04-22T10:00:00Z',
    updated_at: '2026-04-30T10:00:00Z',
    environment_assets: { asset_name: 'dc-server-prod-01', platform: 'onprem', operating_system: 'Windows Server 2022' },
  },
  {
    id: 'demo-f-010',
    scan_id: 'demo-scan-004',
    asset_id: 'demo-asset-rhel-02',
    rule_id: 'RHEL-08-010030',
    organization_id: DEMO_ORG_ID,
    finding_status: 'NotAFinding',
    severity: 'CAT_I',
    finding_details: {
      title: 'RHEL 8 must display the Standard Mandatory DoD Notice and Consent Banner before granting access',
      fix_text: 'Configure /etc/issue and /etc/ssh/sshd_config Banner setting.',
      check_content: 'cat /etc/issue | grep -i "You are accessing"',
      vuln_id: 'V-230225',
    },
    evidence: [{ type: 'screenshot', captured_at: '2026-05-01T08:00:00Z', hash: 'sha256:a3f1...' }],
    remediation_status: 'completed',
    remediation_priority: 1,
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-05-01T08:00:00Z',
    environment_assets: { asset_name: 'api-server-prod-02', platform: 'aws', operating_system: 'RHEL 8.9' },
  },
  {
    id: 'demo-f-011',
    scan_id: 'demo-scan-004',
    asset_id: 'demo-asset-win-01',
    rule_id: 'WN10-CC-000020',
    organization_id: DEMO_ORG_ID,
    finding_status: 'NotAFinding',
    severity: 'CAT_II',
    finding_details: {
      title: 'Autoplay must be turned off for non-volume devices',
      fix_text: 'Configure policy: Computer Configuration >> Windows Settings >> Administrative Templates >> Windows Components >> AutoPlay Policies.',
      check_content: 'Verify AutoPlay is disabled for non-volume devices.',
      vuln_id: 'V-220694',
    },
    evidence: [{ type: 'registry_export', captured_at: '2026-05-02T09:00:00Z', hash: 'sha256:b8e2...' }],
    remediation_status: 'verified',
    remediation_priority: 2,
    created_at: '2026-04-16T09:00:00Z',
    updated_at: '2026-05-02T09:00:00Z',
    environment_assets: { asset_name: 'dc-workstation-14', platform: 'onprem', operating_system: 'Windows 10 22H2' },
  },
  {
    id: 'demo-f-012',
    scan_id: 'demo-scan-004',
    asset_id: 'demo-asset-win-02',
    rule_id: 'WN22-AU-000050',
    organization_id: DEMO_ORG_ID,
    finding_status: 'NotAFinding',
    severity: 'CAT_II',
    finding_details: {
      title: 'Windows Server 2022 must be configured to audit Account Logon - Credential Validation successes',
      fix_text: 'Configure audit policy subcategory: auditpol /set /subcategory:"Credential Validation" /success:enable',
      check_content: 'auditpol /get /subcategory:"Credential Validation"',
      vuln_id: 'V-254462',
    },
    evidence: [{ type: 'auditpol_export', captured_at: '2026-05-03T10:00:00Z', hash: 'sha256:c4a9...' }],
    remediation_status: 'verified',
    remediation_priority: 2,
    created_at: '2026-04-20T11:00:00Z',
    updated_at: '2026-05-03T10:00:00Z',
    environment_assets: { asset_name: 'dc-server-prod-01', platform: 'onprem', operating_system: 'Windows Server 2022' },
  },
];
