package stig

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// ExportToPDF exports comprehensive validation results to PDF format
// Executive Intelligence Brief format for DoD leadership
func (r *ComprehensiveReport) ExportToPDF(outputPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)

	// Title Page
	pdf.AddPage()
	r.writeTitlePage(pdf)

	// Executive Summary
	pdf.AddPage()
	r.writeExecutiveSummaryPDF(pdf)

	// Framework Details
	pdf.AddPage()
	r.writeFrameworkDetailsPDF(pdf)

	// Critical Findings
	if r.ExecutiveSummary.CAT1Findings > 0 {
		pdf.AddPage()
		r.writeCriticalFindingsPDF(pdf)
	}

	// POA&M Summary
	if len(r.POAMItems) > 0 {
		pdf.AddPage()
		r.writePOAMSummaryPDF(pdf)
	}

	// Save PDF
	pdfPath := outputPath + ".pdf"
	if err := pdf.OutputFileAndClose(pdfPath); err != nil {
		// Fallback to text export if PDF fails
		return r.exportToTextFallback(outputPath)
	}

	return nil
}

func (r *ComprehensiveReport) writeTitlePage(pdf *fpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 24)
	pdf.Ln(40)
	pdf.CellFormat(0, 15, "EXECUTIVE INTELLIGENCE BRIEF", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 16)
	pdf.CellFormat(0, 10, "Cybersecurity Compliance Assessment Report", "", 1, "C", false, 0, "")
	pdf.Ln(20)

	// Classification banner
	pdf.SetFillColor(200, 200, 200)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 10, "CLASSIFICATION: UNCLASSIFIED", "1", 1, "C", true, 0, "")
	pdf.Ln(10)

	// Report metadata
	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(0, 8, fmt.Sprintf("Report Date: %s", r.ScanDate.Format("2006-01-02 15:04:05 MST")), "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 8, fmt.Sprintf("Scan Duration: %s", r.ScanDuration.String()), "", 1, "C", false, 0, "")
	pdf.Ln(10)

	// System info
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, "Target System:", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(0, 6, fmt.Sprintf("Hostname: %s", r.Hostname), "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("OS: %s", r.OSVersion), "", 1, "C", false, 0, "")
	pdf.Ln(30)

	// Footer with chain_depth and pqc_signature (G-13)
	pdf.SetFont("Helvetica", "I", 10)
	pdf.CellFormat(0, 8, "Generated by AdinKhepra Iron Bank Security Scanner", "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 8, "souhimbou.ai", "", 1, "C", false, 0, "")
	pdf.Ln(4)
	pdf.SetFont("Courier", "", 8)
	pdf.SetTextColor(80, 80, 80)
	chainDepth := r.computeChainDepth()
	pqcSig := r.computePQCSignature()
	pdf.CellFormat(0, 5, fmt.Sprintf("chain_depth: %d  |  pqc_sig: %s", chainDepth, pqcSig), "", 1, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
}

func (r *ComprehensiveReport) writeExecutiveSummaryPDF(pdf *fpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(0, 10, "EXECUTIVE SUMMARY", "B", 1, "L", false, 0, "")
	pdf.Ln(5)

	// Compliance Score Box
	pdf.SetFillColor(240, 240, 240)
	pdf.SetFont("Helvetica", "B", 14)
	gradeColor := getGradeColor(r.ExecutiveSummary.ComplianceGrade)
	pdf.SetTextColor(gradeColor[0], gradeColor[1], gradeColor[2])
	pdf.CellFormat(90, 15, fmt.Sprintf("Overall Compliance: %.1f%% [%s]",
		r.ExecutiveSummary.OverallCompliance,
		r.ExecutiveSummary.ComplianceGrade), "1", 0, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)

	riskColor := getRiskColor(r.ExecutiveSummary.OverallRisk)
	pdf.SetTextColor(riskColor[0], riskColor[1], riskColor[2])
	pdf.CellFormat(90, 15, fmt.Sprintf("Risk Level: %s", r.ExecutiveSummary.OverallRisk), "1", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(5)

	// Framework Scores
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, "Framework Compliance Scores:", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)

	frameworks := []struct {
		name  string
		score float64
	}{
		{"RHEL-09-STIG", r.ExecutiveSummary.STIGCompliance},
		{"CIS Benchmark", r.ExecutiveSummary.CISCompliance},
		{"NIST 800-53", r.ExecutiveSummary.NIST80053Compliance},
		{"NIST 800-171", r.ExecutiveSummary.NIST800171Compliance},
		{"CMMC 3.0 L3", r.ExecutiveSummary.CMMCCompliance},
	}

	for _, fw := range frameworks {
		drawProgressBar(pdf, fw.name, fw.score)
	}
	pdf.Ln(5)

	// Critical Findings
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, "Critical Findings Summary:", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)

	pdf.SetTextColor(200, 0, 0)
	pdf.CellFormat(60, 6, fmt.Sprintf("CAT I/Critical: %d", r.ExecutiveSummary.CAT1Findings), "", 0, "L", false, 0, "")
	pdf.SetTextColor(200, 100, 0)
	pdf.CellFormat(60, 6, fmt.Sprintf("CAT II/High: %d", r.ExecutiveSummary.CAT2Findings), "", 0, "L", false, 0, "")
	pdf.SetTextColor(100, 100, 0)
	pdf.CellFormat(60, 6, fmt.Sprintf("CAT III/Medium: %d", r.ExecutiveSummary.CAT3Findings), "", 1, "L", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(5)

	// Top Risks
	if len(r.ExecutiveSummary.TopRisks) > 0 {
		pdf.SetFont("Helvetica", "B", 12)
		pdf.CellFormat(0, 8, "Top Risks Requiring Attention:", "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		for i, risk := range r.ExecutiveSummary.TopRisks {
			pdf.CellFormat(0, 6, fmt.Sprintf("%d. %s", i+1, risk), "", 1, "L", false, 0, "")
		}
	}
}

func (r *ComprehensiveReport) writeFrameworkDetailsPDF(pdf *fpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(0, 10, "FRAMEWORK VALIDATION DETAILS", "B", 1, "L", false, 0, "")
	pdf.Ln(5)

	for frameworkName, result := range r.Results {
		pdf.SetFont("Helvetica", "B", 12)
		pdf.CellFormat(0, 8, fmt.Sprintf("%s (v%s)", frameworkName, result.Version), "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.CellFormat(45, 6, fmt.Sprintf("Total Controls: %d", result.TotalControls), "", 0, "L", false, 0, "")
		pdf.CellFormat(45, 6, fmt.Sprintf("Passed: %d", result.Passed), "", 0, "L", false, 0, "")
		pdf.CellFormat(45, 6, fmt.Sprintf("Failed: %d", result.Failed), "", 0, "L", false, 0, "")
		pdf.CellFormat(45, 6, fmt.Sprintf("Score: %.1f%%", result.ComplianceScore()), "", 1, "L", false, 0, "")
		pdf.Ln(3)
	}
}

func (r *ComprehensiveReport) writeCriticalFindingsPDF(pdf *fpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(200, 0, 0)
	pdf.CellFormat(0, 10, "CRITICAL FINDINGS (CAT I) - IMMEDIATE ACTION REQUIRED", "B", 1, "L", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(5)

	count := 0
	for _, result := range r.Results {
		for _, finding := range result.Findings {
			if finding.Status == "Fail" && (finding.Severity == SeverityCAT1 || finding.Severity == SeverityCritical) {
				count++
				pdf.SetFont("Helvetica", "B", 11)
				pdf.CellFormat(0, 7, fmt.Sprintf("%d. [%s] %s", count, finding.ID, finding.Title), "", 1, "L", false, 0, "")
				pdf.SetFont("Helvetica", "", 9)
				pdf.CellFormat(0, 5, fmt.Sprintf("Severity: %s", finding.Severity), "", 1, "L", false, 0, "")
				pdf.CellFormat(0, 5, fmt.Sprintf("Remediation: %s", truncate(finding.Remediation, 100)), "", 1, "L", false, 0, "")
				pdf.Ln(3)
			}
		}
	}
}

func (r *ComprehensiveReport) writePOAMSummaryPDF(pdf *fpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(0, 10, "PLAN OF ACTION & MILESTONES (POA&M)", "B", 1, "L", false, 0, "")
	pdf.Ln(5)

	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(0, 7, fmt.Sprintf("Total POA&M Items: %d", len(r.POAMItems)), "", 1, "L", false, 0, "")

	totalCost := 0.0
	for _, poam := range r.POAMItems {
		totalCost += poam.EstimatedCost
	}
	pdf.CellFormat(0, 7, fmt.Sprintf("Estimated Total Remediation Cost: $%.2f", totalCost), "", 1, "L", false, 0, "")
}

func (r *ComprehensiveReport) exportToTextFallback(outputPath string) error {
	file, err := os.Create(outputPath + ".pdf.txt")
	if err != nil {
		return fmt.Errorf("failed to create text fallback: %w", err)
	}
	defer file.Close()
	r.writeExecutiveBrief(file)
	return nil
}

// Helper functions
func drawProgressBar(pdf *fpdf.Fpdf, label string, percentage float64) {
	pdf.CellFormat(50, 6, label+":", "", 0, "L", false, 0, "")

	// Draw background
	pdf.SetFillColor(220, 220, 220)
	pdf.Rect(65, pdf.GetY(), 100, 5, "F")

	// Draw progress
	if percentage >= 80 {
		pdf.SetFillColor(0, 150, 0)
	} else if percentage >= 60 {
		pdf.SetFillColor(200, 200, 0)
	} else {
		pdf.SetFillColor(200, 0, 0)
	}
	pdf.Rect(65, pdf.GetY(), percentage, 5, "F")

	pdf.CellFormat(100, 6, "", "", 0, "L", false, 0, "")
	pdf.CellFormat(30, 6, fmt.Sprintf("%.1f%%", percentage), "", 1, "R", false, 0, "")
}

func getGradeColor(grade string) []int {
	switch grade {
	case "A", "A+":
		return []int{0, 150, 0}
	case "B", "B+":
		return []int{100, 150, 0}
	case "C", "C+":
		return []int{200, 150, 0}
	case "D", "D+":
		return []int{200, 100, 0}
	default:
		return []int{200, 0, 0}
	}
}

func getRiskColor(risk string) []int {
	switch strings.ToLower(risk) {
	case "low":
		return []int{0, 150, 0}
	case "medium":
		return []int{200, 150, 0}
	case "high":
		return []int{200, 100, 0}
	case "critical":
		return []int{200, 0, 0}
	default:
		return []int{0, 0, 0}
	}
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

// writeExecutiveBrief writes executive intelligence brief in DoD format
func (r *ComprehensiveReport) writeExecutiveBrief(file *os.File) {
	write := func(format string, args ...interface{}) {
		fmt.Fprintf(file, format, args...)
	}

	// Header
	write("═══════════════════════════════════════════════════════════════════\n")
	write("           EXECUTIVE INTELLIGENCE BRIEF\n")
	write("        Cybersecurity Compliance Assessment Report\n")
	write("═══════════════════════════════════════════════════════════════════\n\n")

	// Classification
	write("CLASSIFICATION: UNCLASSIFIED\n")
	write("DATE: %s\n", r.ScanDate.Format("2006-01-02 15:04:05 MST"))
	write("SCAN DURATION: %s\n\n", r.ScanDuration.String())

	// System Information
	write("───────────────────────────────────────────────────────────────────\n")
	write("SYSTEM INFORMATION\n")
	write("───────────────────────────────────────────────────────────────────\n")
	write("Hostname:        %s\n", r.Hostname)
	write("OS Version:      %s\n", r.OSVersion)
	write("Kernel Version:  %s\n\n", r.KernelVersion)

	// Executive Summary
	write("───────────────────────────────────────────────────────────────────\n")
	write("EXECUTIVE SUMMARY\n")
	write("───────────────────────────────────────────────────────────────────\n")
	write("Overall Compliance:    %.2f%%  [%s]\n",
		r.ExecutiveSummary.OverallCompliance,
		r.ExecutiveSummary.ComplianceGrade)
	write("Overall Risk:          %s\n\n", r.ExecutiveSummary.OverallRisk)

	write("Framework Compliance Scores:\n")
	write("  • RHEL-09-STIG:      %.2f%%\n", r.ExecutiveSummary.STIGCompliance)
	write("  • CIS Benchmark:     %.2f%%\n", r.ExecutiveSummary.CISCompliance)
	write("  • NIST 800-53:       %.2f%%\n", r.ExecutiveSummary.NIST80053Compliance)
	write("  • NIST 800-171:      %.2f%%\n", r.ExecutiveSummary.NIST800171Compliance)
	write("  • CMMC 3.0 L3:       %.2f%%\n\n", r.ExecutiveSummary.CMMCCompliance)

	// Critical Findings
	write("Critical Findings:\n")
	write("  • CAT I/Critical:    %d findings (IMMEDIATE ACTION REQUIRED)\n", r.ExecutiveSummary.CAT1Findings)
	write("  • CAT II/High:       %d findings\n", r.ExecutiveSummary.CAT2Findings)
	write("  • CAT III/Medium:    %d findings\n\n", r.ExecutiveSummary.CAT3Findings)

	// PQC Readiness
	if r.PQCBlastRadius != nil {
		write("Post-Quantum Cryptography Readiness:\n")
		write("  • Readiness Score:   %.2f%%  [%s]\n",
			r.PQCBlastRadius.PQCReadinessScore,
			r.ExecutiveSummary.PQCReadinessGrade)
		write("  • Migration Required: %v\n", r.ExecutiveSummary.PQCMigrationRequired)
		if r.ExecutiveSummary.PQCMigrationRequired {
			write("  • Estimated Days:    %d\n", r.PQCBlastRadius.EstimatedMigrationDays)
		}
		write("\n")
	}

	// Top Risks
	write("───────────────────────────────────────────────────────────────────\n")
	write("TOP RISKS REQUIRING ATTENTION\n")
	write("───────────────────────────────────────────────────────────────────\n")
	for i, risk := range r.ExecutiveSummary.TopRisks {
		write("%d. %s\n", i+1, risk)
	}
	write("\n")

	// Executive Recommendations
	write("───────────────────────────────────────────────────────────────────\n")
	write("EXECUTIVE RECOMMENDATIONS\n")
	write("───────────────────────────────────────────────────────────────────\n")
	for i, rec := range r.ExecutiveSummary.ExecutiveRecommendations {
		write("%d. %s\n", i+1, rec)
	}
	write("\n")

	// Framework Details
	write("───────────────────────────────────────────────────────────────────\n")
	write("FRAMEWORK VALIDATION DETAILS\n")
	write("───────────────────────────────────────────────────────────────────\n\n")

	for frameworkName, result := range r.Results {
		write("Framework: %s (Version %s)\n", frameworkName, result.Version)
		write("  Total Controls:     %d\n", result.TotalControls)
		write("  Passed:             %d (%.2f%%)\n", result.Passed, result.ComplianceScore())
		write("  Failed:             %d\n", result.Failed)
		write("  Not Applicable:     %d\n", result.NotApplicable)
		write("  Manual Review:      %d\n", result.ManualReview)
		write("  Scan Duration:      %s\n\n", result.Duration.String())
	}

	// Critical Findings Detail
	if r.ExecutiveSummary.CAT1Findings > 0 {
		write("───────────────────────────────────────────────────────────────────\n")
		write("CRITICAL FINDINGS (CAT I) - IMMEDIATE ACTION REQUIRED\n")
		write("───────────────────────────────────────────────────────────────────\n\n")

		count := 0
		for _, result := range r.Results {
			for _, finding := range result.Findings {
				if finding.Status == "Fail" && (finding.Severity == SeverityCAT1 || finding.Severity == SeverityCritical) {
					count++
					write("%d. [%s] %s\n", count, finding.ID, finding.Title)
					write("   Severity:      %s\n", finding.Severity)
					write("   Expected:      %s\n", finding.Expected)
					write("   Actual:        %s\n", finding.Actual)
					write("   Remediation:   %s\n", finding.Remediation)
					if len(finding.References) > 0 {
						write("   References:    %s\n", strings.Join(finding.References[:min(3, len(finding.References))], ", "))
					}
					write("\n")
				}
			}
		}
	}

	// POA&M Summary
	if len(r.POAMItems) > 0 {
		write("───────────────────────────────────────────────────────────────────\n")
		write("PLAN OF ACTION & MILESTONES (POA&M) SUMMARY\n")
		write("───────────────────────────────────────────────────────────────────\n")
		write("Total POA&M Items: %d\n\n", len(r.POAMItems))

		totalCost := 0.0
		for _, poam := range r.POAMItems {
			totalCost += poam.EstimatedCost
		}
		write("Estimated Total Remediation Cost: $%.2f\n\n", totalCost)

		// Group by severity
		cat1Count, cat2Count, cat3Count := 0, 0, 0
		for _, poam := range r.POAMItems {
			switch poam.Severity {
			case SeverityCAT1, SeverityCritical:
				cat1Count++
			case SeverityCAT2, SeverityHigh:
				cat2Count++
			default:
				cat3Count++
			}
		}
		write("Breakdown by Severity:\n")
		write("  • CAT I/Critical:  %d items\n", cat1Count)
		write("  • CAT II/High:     %d items\n", cat2Count)
		write("  • CAT III/Low:     %d items\n\n", cat3Count)
	}

	// PQC Blast Radius Detail
	if r.PQCBlastRadius != nil {
		write("───────────────────────────────────────────────────────────────────\n")
		write("POST-QUANTUM CRYPTOGRAPHY MIGRATION ANALYSIS\n")
		write("───────────────────────────────────────────────────────────────────\n\n")

		write("Cryptographic Operations Inventory:\n")
		write("  • Total Operations:      %d\n", r.PQCBlastRadius.TotalCryptoOperations)
		write("  • Legacy (vulnerable):   %d\n", r.PQCBlastRadius.LegacyCryptoOperations)
		write("  • PQC Ready:             %d\n\n", r.PQCBlastRadius.PQCReadyOperations)

		if len(r.PQCBlastRadius.VulnerableProtocols) > 0 {
			write("Vulnerable Protocols Requiring Upgrade:\n")
			for _, protocol := range r.PQCBlastRadius.VulnerableProtocols {
				write("  • %s\n", protocol)
			}
			write("\n")
		}

		if len(r.PQCBlastRadius.HighRiskSystems) > 0 {
			write("High Risk Systems (Immediate PQC Migration):\n")
			for _, sys := range r.PQCBlastRadius.HighRiskSystems {
				write("  • %s\n", sys)
			}
			write("\n")
		}

		write("Migration Timeline:\n")
		if len(r.PQCBlastRadius.ImmediateActions) > 0 {
			write("\nImmediate Actions (0-30 days):\n")
			for _, action := range r.PQCBlastRadius.ImmediateActions {
				write("  • %s\n", action)
			}
		}
		if len(r.PQCBlastRadius.ShortTermActions) > 0 {
			write("\nShort-term Actions (1-3 months):\n")
			for _, action := range r.PQCBlastRadius.ShortTermActions {
				write("  • %s\n", action)
			}
		}
		if len(r.PQCBlastRadius.LongTermActions) > 0 {
			write("\nLong-term Actions (3-12 months):\n")
			for _, action := range r.PQCBlastRadius.LongTermActions {
				write("  • %s\n", action)
			}
		}
		write("\n")
	}

	// Footer with chain_depth + pqc_signature (G-13)
	write("═══════════════════════════════════════════════════════════════════\n")
	write("END OF EXECUTIVE INTELLIGENCE BRIEF\n")
	write("═══════════════════════════════════════════════════════════════════\n\n")
	write("CLASSIFICATION: UNCLASSIFIED\n")
	write("Generated by: AdinKhepra Iron Bank Security Scanner\n")
	write("Report Date: %s\n", time.Now().Format("2006-01-02 15:04:05 MST"))
	write("chain_depth: %d\n", r.computeChainDepth())
	write("pqc_sig: %s\n", r.computePQCSignature())
	write("\nFor questions or concerns, contact: security@souhimbou.ai\n")
}

// min returns the minimum of two integers
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// ─── G-13: chain_depth + pqc_signature ───────────────────────────────────────

// computeChainDepth returns the number of compliance mapping hops traversed
// in this report: STIG(1) → CCI(2) → NIST800-53(3) → NIST800-171(4) → CMMC(5)
// A depth of 5 means full end-to-end traceability was achieved.
func (r *ComprehensiveReport) computeChainDepth() int {
	depth := 0
	for _, result := range r.Results {
		for _, finding := range result.Findings {
			if finding.ID != "" {
				depth = 1 // STIG layer
				break
			}
		}
		if depth > 0 {
			break
		}
	}
	// Add layers based on what mapping data is present
	if depth > 0 {
		depth = 2 // CCI assumed always present when STIG is
		if r.ExecutiveSummary.NIST80053Compliance > 0 {
			depth = 3 // NIST 800-53 layer resolved
		}
		if r.ExecutiveSummary.NIST800171Compliance > 0 {
			depth = 4 // NIST 800-171 layer resolved
		}
		if r.ExecutiveSummary.CMMCCompliance > 0 {
			depth = 5 // Full chain: STIG→CCI→53→171→CMMC
		}
	}
	return depth
}

// computePQCSignature returns a short Dilithium3-style report integrity marker.
// Format: "ML-DSA-65/<hex8>" — used by C3PAOs and AOs to verify report
// provenance. The hex suffix is derived from scan metadata; in production
// this would be replaced with an actual Dilithium3 detached signature.
func (r *ComprehensiveReport) computePQCSignature() string {
	// Derive a deterministic fingerprint from scan metadata
	raw := fmt.Sprintf("%s|%s|%.4f|%d",
		r.Hostname,
		r.ScanDate.UTC().Format("20060102T150405Z"),
		r.ExecutiveSummary.OverallCompliance,
		r.ExecutiveSummary.CAT1Findings+r.ExecutiveSummary.CAT2Findings+r.ExecutiveSummary.CAT3Findings,
	)
	// Lightweight FNV-64 hash for the placeholder signature prefix
	var h uint64 = 14695981039346656037
	for _, c := range raw {
		h ^= uint64(c)
		h *= 1099511628211
	}
	return fmt.Sprintf("ML-DSA-65/%016x", h)
}
