package stig

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-pdf/fpdf"
)

// ─── SSP PDF Export ───────────────────────────────────────────────────────────

// SSPExportData holds the data needed to render an SSP PDF.
// This avoids importing cmd-level types from pkg/stig.
type SSPExportData struct {
	SystemName           string
	SystemAbbreviation   string
	ResponsibleOrg       string
	SystemOwner          string
	ISSO                 string
	AuthorizingOfficial  string
	ImpactLevel          string
	CUICategories        []string
	SystemDescription    string
	SystemEnvironment    string
	BoundaryDescription  string
	ApplicableLaws       []string
	Version              string
	GeneratedAt          time.Time
	LastUpdatedAt        time.Time
	DAGChainDepth        int
	PQCSignature         string

	// Control stats
	TotalControls     int
	Implemented       int
	FailedScan        int
	Planned           int
	CompletionPercent float64

	// Control table: controlID → status
	Controls map[string]string
}

// ExportSSPToPDF produces a binary PDF for the SSP document at outputPath.
func ExportSSPToPDF(doc *SSPExportData, outputPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(18, 18, 18)
	pdf.SetAutoPageBreak(true, 18)

	// ── Title Page ──────────────────────────────────────────────────────────
	pdf.AddPage()
	writeSSPTitlePage(pdf, doc)

	// ── Executive Summary ───────────────────────────────────────────────────
	pdf.AddPage()
	writeSSPSummary(pdf, doc)

	// ── Control Table ───────────────────────────────────────────────────────
	if len(doc.Controls) > 0 {
		pdf.AddPage()
		writeSSPControlTable(pdf, doc)
	}

	return pdf.OutputFileAndClose(outputPath)
}

func writeSSPTitlePage(pdf *fpdf.Fpdf, doc *SSPExportData) {
	// Header banner
	pdf.SetFillColor(15, 30, 60) // DoD navy
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 8, "CLASSIFICATION: UNCLASSIFIED // CONTROLLED DEFENSE INFORMATION", "", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(12)

	// Title
	pdf.SetFont("Helvetica", "B", 22)
	pdf.CellFormat(0, 12, "SYSTEM SECURITY PLAN (SSP)", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 14)
	pdf.CellFormat(0, 8, "NIST SP 800-18 / CMMC Level 2", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	// Divider
	pdf.SetDrawColor(15, 30, 60)
	pdf.Line(18, pdf.GetY(), 192, pdf.GetY())
	pdf.Ln(6)

	// Metadata table
	pdf.SetFont("Helvetica", "B", 11)
	row := func(label, value string) {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(60, 7, label, "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.CellFormat(0, 7, value, "", 1, "L", false, 0, "")
	}
	row("System Name:", doc.SystemName)
	if doc.SystemAbbreviation != "" {
		row("Abbreviation:", doc.SystemAbbreviation)
	}
	row("Organization:", doc.ResponsibleOrg)
	row("System Owner:", doc.SystemOwner)
	row("ISSO:", doc.ISSO)
	if doc.AuthorizingOfficial != "" {
		row("Authorizing Official:", doc.AuthorizingOfficial)
	}
	row("Impact Level:", doc.ImpactLevel)
	row("Version:", doc.Version)
	row("Generated:", doc.GeneratedAt.Format("January 2, 2006"))
	row("Last Updated:", doc.LastUpdatedAt.Format("January 2, 2006"))

	// Applicable laws
	if len(doc.ApplicableLaws) > 0 {
		pdf.Ln(4)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(0, 7, "Applicable Requirements:", "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
		for _, law := range doc.ApplicableLaws {
			pdf.CellFormat(8, 6, "•", "", 0, "L", false, 0, "")
			pdf.CellFormat(0, 6, law, "", 1, "L", false, 0, "")
		}
	}

	// Footer
	pdf.Ln(8)
	pdf.SetFont("Courier", "", 8)
	pdf.SetTextColor(80, 80, 80)
	if doc.DAGChainDepth > 0 {
		pdf.CellFormat(0, 5, fmt.Sprintf("chain_depth: %d  |  pqc_sig: %s", doc.DAGChainDepth, doc.PQCSignature), "", 1, "C", false, 0, "")
	}
	pdf.SetFont("Helvetica", "I", 8)
	pdf.CellFormat(0, 5, "Generated by KHEPRA Protocol — NouchiX / SecRed Knowledge Inc.", "", 1, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
}

func writeSSPSummary(pdf *fpdf.Fpdf, doc *SSPExportData) {
	sectionHeader(pdf, "1. SYSTEM IDENTIFICATION & OVERVIEW")

	pdf.SetFont("Helvetica", "", 10)
	if doc.SystemDescription != "" {
		pdf.MultiCell(0, 6, doc.SystemDescription, "", "L", false)
		pdf.Ln(4)
	}
	if doc.SystemEnvironment != "" {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(0, 6, "Environment:", "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(0, 6, doc.SystemEnvironment, "", "L", false)
		pdf.Ln(4)
	}
	if doc.BoundaryDescription != "" {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(0, 6, "System Boundary:", "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(0, 6, doc.BoundaryDescription, "", "L", false)
		pdf.Ln(4)
	}

	sectionHeader(pdf, "2. SECURITY CONTROL COVERAGE")

	// Score box
	pct := doc.CompletionPercent
	r, g, b := scoreColor(pct)
	pdf.SetFillColor(r, g, b)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(0, 12, fmt.Sprintf("Implementation Coverage: %.1f%%", pct), "1", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(4)

	pdf.SetFont("Helvetica", "", 10)
	row4 := func(a, b, c, d string) {
		w := float64(174) / 4
		pdf.CellFormat(w, 7, a, "1", 0, "C", false, 0, "")
		pdf.CellFormat(w, 7, b, "1", 0, "C", false, 0, "")
		pdf.CellFormat(w, 7, c, "1", 0, "C", false, 0, "")
		pdf.CellFormat(w, 7, d, "1", 1, "C", false, 0, "")
	}
	pdf.SetFont("Helvetica", "B", 9)
	row4("Total Controls", "Implemented", "Failed (POAM)", "Planned")
	pdf.SetFont("Helvetica", "", 10)
	row4(
		fmt.Sprintf("%d", doc.TotalControls),
		fmt.Sprintf("%d", doc.Implemented),
		fmt.Sprintf("%d", doc.FailedScan),
		fmt.Sprintf("%d", doc.Planned),
	)
}

func writeSSPControlTable(pdf *fpdf.Fpdf, doc *SSPExportData) {
	sectionHeader(pdf, "3. CONTROL IMPLEMENTATION TABLE")

	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(230, 230, 240)
	pdf.CellFormat(50, 7, "Control ID", "1", 0, "C", true, 0, "")
	pdf.CellFormat(0, 7, "Implementation Status", "1", 1, "C", true, 0, "")

	pdf.SetFont("Helvetica", "", 9)
	alt := false
	for id, status := range doc.Controls {
		if alt {
			pdf.SetFillColor(248, 248, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		alt = !alt

		// Color-code status
		switch status {
		case "IMPLEMENTED":
			pdf.SetTextColor(0, 120, 0)
		case "FAILED_SCAN":
			pdf.SetTextColor(180, 0, 0)
		case "PLANNED":
			pdf.SetTextColor(150, 100, 0)
		default:
			pdf.SetTextColor(80, 80, 80)
		}

		pdf.CellFormat(50, 6, id, "1", 0, "L", true, 0, "")
		pdf.CellFormat(0, 6, status, "1", 1, "L", true, 0, "")
		pdf.SetTextColor(0, 0, 0)
	}
}

// ─── POAM PDF Export ──────────────────────────────────────────────────────────

// POAMExportItem is a single POAM item suitable for PDF rendering.
type POAMExportItem struct {
	ID                  string
	ControlID           string
	Weakness            string
	Severity            string
	Status              string
	DollarImpact        float64
	PriorityScore       float64
	EstimatedDays       int
	ScheduledCompletion time.Time
	PointOfContact      string
	MilestoneActions    []string
}

// POAMExportData holds all data for rendering a POAM PDF.
type POAMExportData struct {
	System        string
	GeneratedAt   time.Time
	TotalExposure float64
	Items         []POAMExportItem
	DAGChainDepth int
	PQCSignature  string
}

// ExportPOAMToPDF produces a binary PDF for a POAM document at outputPath.
func ExportPOAMToPDF(data *POAMExportData, outputPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(18, 18, 18)
	pdf.SetAutoPageBreak(true, 18)

	pdf.AddPage()
	writePOAMTitlePage(pdf, data)

	if len(data.Items) > 0 {
		pdf.AddPage()
		writePOAMSummaryTable(pdf, data)

		pdf.AddPage()
		writePOAMDetailSection(pdf, data)
	}

	return pdf.OutputFileAndClose(outputPath)
}

func writePOAMTitlePage(pdf *fpdf.Fpdf, data *POAMExportData) {
	// Header banner
	pdf.SetFillColor(15, 30, 60)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 8, "CLASSIFICATION: UNCLASSIFIED // CONTROLLED DEFENSE INFORMATION", "", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(12)

	pdf.SetFont("Helvetica", "B", 22)
	pdf.CellFormat(0, 12, "PLAN OF ACTION & MILESTONES (POAM)", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 14)
	pdf.CellFormat(0, 8, "NIST SP 800-171A | CMMC Level 2 Assessment", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	pdf.SetDrawColor(15, 30, 60)
	pdf.Line(18, pdf.GetY(), 192, pdf.GetY())
	pdf.Ln(6)

	row := func(label, value string) {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(60, 7, label, "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.CellFormat(0, 7, value, "", 1, "L", false, 0, "")
	}
	row("System:", data.System)
	row("Generated:", data.GeneratedAt.Format("January 2, 2006"))
	row("Total Open Items:", fmt.Sprintf("%d", len(data.Items)))
	row("Total Financial Exposure:", fmtDollars(data.TotalExposure))

	// Footer
	pdf.Ln(8)
	pdf.SetFont("Courier", "", 8)
	pdf.SetTextColor(80, 80, 80)
	if data.DAGChainDepth > 0 {
		pdf.CellFormat(0, 5, fmt.Sprintf("chain_depth: %d  |  pqc_sig: %s", data.DAGChainDepth, data.PQCSignature), "", 1, "C", false, 0, "")
	}
	pdf.SetFont("Helvetica", "I", 8)
	pdf.CellFormat(0, 5, "Generated by KHEPRA Protocol — NouchiX / SecRed Knowledge Inc.", "", 1, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
}

func writePOAMSummaryTable(pdf *fpdf.Fpdf, data *POAMExportData) {
	sectionHeader(pdf, "POAM REGISTER — PRIORITY SORTED BY DOLLAR IMPACT")

	// Column widths: ID, ControlID, Severity, $Impact, Priority, Due Date, Status
	colW := []float64{28, 38, 22, 30, 22, 26, 28}
	headers := []string{"POAM ID", "Control ID", "Severity", "$ Impact", "Priority", "Due Date", "Status"}

	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetFillColor(230, 230, 240)
	for i, h := range headers {
		pdf.CellFormat(colW[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "", 8)
	alt := false
	for _, item := range data.Items {
		if alt {
			pdf.SetFillColor(248, 248, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		alt = !alt

		// Color severity
		switch item.Severity {
		case "CAT I", "critical":
			pdf.SetTextColor(180, 0, 0)
		case "CAT II", "high":
			pdf.SetTextColor(180, 80, 0)
		default:
			pdf.SetTextColor(0, 0, 0)
		}

		vals := []string{
			item.ID,
			item.ControlID,
			item.Severity,
			fmt.Sprintf("$%.0f", item.DollarImpact),
			fmt.Sprintf("%.0f", item.PriorityScore),
			item.ScheduledCompletion.Format("2006-01-02"),
			item.Status,
		}
		for i, v := range vals {
			pdf.CellFormat(colW[i], 6, v, "1", 0, "C", true, 0, "")
		}
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(-1)
	}
}

func writePOAMDetailSection(pdf *fpdf.Fpdf, data *POAMExportData) {
	sectionHeader(pdf, "DETAILED FINDINGS")

	for _, item := range data.Items {
		// Check if we need a new page
		if pdf.GetY() > 240 {
			pdf.AddPage()
		}

		// Item header
		pdf.SetFillColor(230, 230, 240)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(0, 7, fmt.Sprintf("%s — %s", item.ID, item.ControlID), "1", 1, "L", true, 0, "")

		detailRow := func(label, value string) {
			pdf.SetFont("Helvetica", "B", 9)
			pdf.CellFormat(45, 6, label, "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "", 9)
			pdf.CellFormat(0, 6, value, "", 1, "L", false, 0, "")
		}

		// Severity with color
		switch item.Severity {
		case "CAT I", "critical":
			pdf.SetTextColor(180, 0, 0)
		case "CAT II", "high":
			pdf.SetTextColor(180, 80, 0)
		default:
			pdf.SetTextColor(0, 0, 0)
		}
		detailRow("Severity:", item.Severity)
		pdf.SetTextColor(0, 0, 0)

		detailRow("Status:", item.Status)
		detailRow("Dollar Impact:", fmt.Sprintf("$%.0f USD", item.DollarImpact))
		detailRow("Priority Score:", fmt.Sprintf("%.0f", item.PriorityScore))
		detailRow("Estimated Remediation:", fmt.Sprintf("%d days", item.EstimatedDays))
		detailRow("Scheduled Completion:", item.ScheduledCompletion.Format("January 2, 2006"))
		detailRow("Point of Contact:", item.PointOfContact)

		if item.Weakness != "" {
			pdf.SetFont("Helvetica", "B", 9)
			pdf.CellFormat(0, 6, "Weakness:", "", 1, "L", false, 0, "")
			pdf.SetFont("Helvetica", "", 9)
			pdf.MultiCell(0, 5, item.Weakness, "", "L", false)
		}

		if len(item.MilestoneActions) > 0 {
			pdf.SetFont("Helvetica", "B", 9)
			pdf.CellFormat(0, 6, "Milestone Actions:", "", 1, "L", false, 0, "")
			pdf.SetFont("Helvetica", "", 9)
			for _, action := range item.MilestoneActions {
				pdf.CellFormat(6, 5, "•", "", 0, "L", false, 0, "")
				pdf.MultiCell(0, 5, action, "", "L", false)
			}
		}

		pdf.Ln(4)
		pdf.SetDrawColor(200, 200, 200)
		pdf.Line(18, pdf.GetY(), 192, pdf.GetY())
		pdf.Ln(4)
	}
}

// ─── Blast Radius PDF Export ──────────────────────────────────────────────────

// BlastRadiusAsset represents a single cryptographic asset for PDF rendering.
type BlastRadiusAsset struct {
	Name      string
	Algorithm string
	NTIScore  float64
	Phase     string
}

// BlastRadiusExportData holds all data for the Quantum-Readiness PDF.
type BlastRadiusExportData struct {
	System        string
	GeneratedAt   time.Time
	TotalAssets   int
	HighRisk      int
	AvgNTIScore   float64
	Assets        []BlastRadiusAsset
	Phase1Actions []string
	Phase2Actions []string
	Phase3Actions []string
	DAGChainDepth int
	PQCSignature  string
}

// ExportBlastRadiusToPDF produces a binary PDF for the Quantum-Readiness Blast Radius report.
func ExportBlastRadiusToPDF(data *BlastRadiusExportData, outputPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(18, 18, 18)
	pdf.SetAutoPageBreak(true, 18)

	pdf.AddPage()
	writeBlastRadiusTitlePage(pdf, data)

	pdf.AddPage()
	writeBlastRadiusAssetTable(pdf, data)

	if len(data.Phase1Actions)+len(data.Phase2Actions)+len(data.Phase3Actions) > 0 {
		pdf.AddPage()
		writeBlastRadiusMigrationRoadmap(pdf, data)
	}

	return pdf.OutputFileAndClose(outputPath)
}

func writeBlastRadiusTitlePage(pdf *fpdf.Fpdf, data *BlastRadiusExportData) {
	pdf.SetFillColor(60, 0, 80) // deep purple — quantum theme
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 8, "CLASSIFICATION: UNCLASSIFIED // QUANTUM-SENSITIVE", "", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(12)

	pdf.SetFont("Helvetica", "B", 20)
	pdf.CellFormat(0, 12, "QUANTUM-READINESS BLAST RADIUS REPORT", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 13)
	pdf.CellFormat(0, 8, "Nkyinkyim Threat Index (NTI) — Q-Day Exposure Assessment", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	pdf.SetDrawColor(60, 0, 80)
	pdf.Line(18, pdf.GetY(), 192, pdf.GetY())
	pdf.Ln(6)

	row := func(label, value string) {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(70, 7, label, "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.CellFormat(0, 7, value, "", 1, "L", false, 0, "")
	}
	row("System:", data.System)
	row("Assessment Date:", data.GeneratedAt.Format("January 2, 2006"))
	row("Total Cryptographic Assets:", fmt.Sprintf("%d", data.TotalAssets))
	row("High-Risk Assets (NTI ≥ 8.0):", fmt.Sprintf("%d", data.HighRisk))
	row("Average NTI Score:", fmt.Sprintf("%.1f / 10", data.AvgNTIScore))
	row("Q-Day Planning Horizon:", "2030–2035 (NIST/NSA guidance)")

	// NTI Risk gauge
	pdf.Ln(6)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 7, "NTI Risk Level:", "", 1, "L", false, 0, "")
	r2, g2, b2 := ntiColor(data.AvgNTIScore)
	pdf.SetFillColor(r2, g2, b2)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.CellFormat(0, 10, fmt.Sprintf("%.1f / 10 — %s", data.AvgNTIScore, ntiLabel(data.AvgNTIScore)), "1", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)

	// Footer
	pdf.Ln(8)
	pdf.SetFont("Courier", "", 8)
	pdf.SetTextColor(80, 80, 80)
	if data.DAGChainDepth > 0 {
		pdf.CellFormat(0, 5, fmt.Sprintf("chain_depth: %d  |  pqc_sig: %s", data.DAGChainDepth, data.PQCSignature), "", 1, "C", false, 0, "")
	}
	pdf.SetFont("Helvetica", "I", 8)
	pdf.CellFormat(0, 5, "Generated by KHEPRA Protocol — NouchiX / SecRed Knowledge Inc. — USPTO #73565085", "", 1, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
}

func writeBlastRadiusAssetTable(pdf *fpdf.Fpdf, data *BlastRadiusExportData) {
	sectionHeader(pdf, "CRYPTOGRAPHIC ASSET INVENTORY — NTI SCORED")

	colW := []float64{60, 44, 26, 44}
	headers := []string{"Asset", "Algorithm", "NTI Score", "Migration Phase"}

	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(230, 220, 240)
	for i, h := range headers {
		pdf.CellFormat(colW[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "", 9)
	for _, asset := range data.Assets {
		r2, g2, b2 := ntiColor(asset.NTIScore)
		pdf.SetTextColor(r2, g2, b2)
		pdf.SetFillColor(255, 255, 255)

		pdf.CellFormat(colW[0], 6, asset.Name, "1", 0, "L", true, 0, "")
		pdf.CellFormat(colW[1], 6, asset.Algorithm, "1", 0, "L", true, 0, "")
		pdf.CellFormat(colW[2], 6, fmt.Sprintf("%.1f", asset.NTIScore), "1", 0, "C", true, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.CellFormat(colW[3], 6, asset.Phase, "1", 1, "C", true, 0, "")
	}
}

func writeBlastRadiusMigrationRoadmap(pdf *fpdf.Fpdf, data *BlastRadiusExportData) {
	sectionHeader(pdf, "PQC MIGRATION ROADMAP")

	writePhase := func(title, subtitle string, actions []string) {
		if len(actions) == 0 {
			return
		}
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(0, 7, title, "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "I", 9)
		pdf.CellFormat(0, 5, subtitle, "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
		for _, action := range actions {
			pdf.CellFormat(6, 5, "•", "", 0, "L", false, 0, "")
			pdf.MultiCell(0, 5, action, "", "L", false)
		}
		pdf.Ln(3)
	}

	writePhase("Phase 1 — Immediate (0–6 months)", "Migrate highest-NTI assets to ML-DSA-65 / ML-KEM-1024", data.Phase1Actions)
	writePhase("Phase 2 — Near-Term (6–18 months)", "Transition remaining RSA/ECC infrastructure", data.Phase2Actions)
	writePhase("Phase 3 — Long-Term (18–36 months)", "Full PQC posture — NIST FIPS 204/203 compliant", data.Phase3Actions)
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

// fmtDollars formats a float64 as a dollar amount with comma thousands separators.
// Go's fmt does not support %,d or %,.0f, so we use integer arithmetic.
func fmtDollars(v float64) string {
	n := int64(v)
	s := strconv.FormatInt(n, 10)
	out := make([]byte, 0, len(s)+len(s)/3+1)
	for i, c := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, byte(c))
	}
	return "$" + string(out) + " USD"
}

func sectionHeader(pdf *fpdf.Fpdf, title string) {
	pdf.SetFillColor(15, 30, 60)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 8, title, "", 1, "L", true, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(4)
}

func scoreColor(pct float64) (int, int, int) {
	switch {
	case pct >= 80:
		return 0, 120, 0 // green
	case pct >= 60:
		return 180, 130, 0 // amber
	default:
		return 180, 0, 0 // red
	}
}

func ntiColor(score float64) (int, int, int) {
	switch {
	case score >= 9.0:
		return 180, 0, 0 // critical red
	case score >= 7.0:
		return 180, 80, 0 // high orange
	case score >= 5.0:
		return 180, 150, 0 // medium amber
	default:
		return 0, 120, 0 // low green
	}
}

func ntiLabel(score float64) string {
	switch {
	case score >= 9.0:
		return "CRITICAL — Immediate PQC migration required"
	case score >= 7.0:
		return "HIGH — Priority migration within 6 months"
	case score >= 5.0:
		return "MEDIUM — Plan migration within 18 months"
	default:
		return "LOW — Monitor; migrate within 3 years"
	}
}
