package sekhem

// waf_rules.go — SEKHEM WAF rule implementations.
//
// Rule catalogue:
//   SEKHEM-BYPASS  Allow-list: health probes + NPM Docker gateway
//   SEKHEM-001     SQL injection detection (headers + URL + body)
//   SEKHEM-002     Cross-site scripting (XSS) detection
//   SEKHEM-003     Path traversal detection
//   SEKHEM-004     Oversized body guard (applied in WAFShield.GinHandler before rule loop)
//   SEKHEM-005     Invalid UTF-8 in request headers
//   SEKHEM-006     Missing or forged Host header
//   SEKHEM-007     Per-IP rate limit (100 req/min) — replaces the standalone RateLimitMiddleware
//   SEKHEM-008     Malicious User-Agent strings (scanners, exploit frameworks)
//
// All rules implement WAFRule and return a *WAFRuleResult (nil = pass).

import (
	"io"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	"github.com/nouchix/PQC-Khepra-MCP/pkg/maat"
)

// WAFAction enumerates what the WAF does with a matched request.
type WAFAction int

const (
	WAFActionAllow     WAFAction = iota // rule matched but explicitly allow (bypass)
	WAFActionBlock                      // hard block — 403 + Crowdsec decision
	WAFActionChallenge                  // soft block — 429 Retry-After
	WAFActionBypass                     // path/CIDR bypass — no rule run
)

// WAFRuleResult is returned by a rule that matched. nil means the rule passed.
type WAFRuleResult struct {
	RuleID        string
	Action        WAFAction
	Severity      maat.Severity
	Certainty     float64 // 0.0–1.0
	CorrelationID string  // pre-generated by caller in WAFShield
}

// WAFRule is the interface every rule must implement.
type WAFRule interface {
	// Inspect examines the request and returns nil (pass) or a result (match).
	Inspect(r *http.Request) *WAFRuleResult
	// ID returns the rule identifier used in metrics and logs.
	ID() string
}

// defaultRules constructs the ordered rule slice for a WAFShield.
// Rules are evaluated in order; the first match terminates inspection.
func defaultRules(shield *WAFShield) []WAFRule {
	return []WAFRule{
		newSQLiRule(),
		newXSSRule(),
		newPathTraversalRule(),
		newInvalidUTF8Rule(),
		newInvalidHostRule(),
		newRateLimitRule(),
		newMaliciousUARule(),
	}
}

// ─── SEKHEM-001: SQL Injection ────────────────────────────────────────────────

var sqliPattern = regexp.MustCompile(
	`(?i)(\b(select|insert|update|delete|drop|create|alter|truncate|exec|execute|union|having|where|group\s+by|order\s+by)\b` +
		`|--\s*$|;\s*--|\/\*.*?\*\/` +
		`|'\s*(or|and)\s+'?\d+\s*=\s*\d+` +
		`|'\s*(or|and)\s+'[^']*'\s*=\s*'[^']*'` +
		`|xp_\w+|sp_\w+` +
		`|\bwaitfor\s+delay\b|\bsleep\s*\(\s*\d` +
		`|\bload_file\s*\(|\binto\s+outfile\b)`)

type sqliRule struct{}

func newSQLiRule() WAFRule { return &sqliRule{} }

func (r *sqliRule) ID() string { return "SEKHEM-001" }

func (r *sqliRule) Inspect(req *http.Request) *WAFRuleResult {
	if scanString(req, sqliPattern) {
		return &WAFRuleResult{
			RuleID:        r.ID(),
			Action:        WAFActionBlock,
			Severity:      maat.SeverityCatastrophic,
			Certainty:     0.90,
			CorrelationID: newCorrelationID(),
		}
	}
	return nil
}

// ─── SEKHEM-002: XSS ─────────────────────────────────────────────────────────

var xssPattern = regexp.MustCompile(
	`(?i)(<\s*script[\s>]|javascript\s*:|vbscript\s*:|on\w+\s*=` +
		`|<\s*iframe[\s>]|<\s*object[\s>]|<\s*embed[\s>]` +
		`|<\s*img[^>]+\bon\w+\s*=` +
		`|eval\s*\(|document\s*\.\s*cookie|document\s*\.\s*write` +
		`|window\s*\.\s*location|alert\s*\(|confirm\s*\(|prompt\s*\()`)

type xssRule struct{}

func newXSSRule() WAFRule { return &xssRule{} }

func (r *xssRule) ID() string { return "SEKHEM-002" }

func (r *xssRule) Inspect(req *http.Request) *WAFRuleResult {
	if scanString(req, xssPattern) {
		return &WAFRuleResult{
			RuleID:        r.ID(),
			Action:        WAFActionBlock,
			Severity:      maat.SeveritySevere,
			Certainty:     0.88,
			CorrelationID: newCorrelationID(),
		}
	}
	return nil
}

// ─── SEKHEM-003: Path Traversal ──────────────────────────────────────────────

var pathTraversalPattern = regexp.MustCompile(
	`(?i)(\.\.[\\/]|%2e%2e[\\/]|%252e%252e[\\/]` +
		`|\.\.%2f|%2e\.%2f|%2e%2e%2f` +
		`|\/etc\/passwd|\/etc\/shadow|\/proc\/self` +
		`|\\windows\\system32|cmd\.exe|powershell\.exe)`)

type pathTraversalRule struct{}

func newPathTraversalRule() WAFRule { return &pathTraversalRule{} }

func (r *pathTraversalRule) ID() string { return "SEKHEM-003" }

func (r *pathTraversalRule) Inspect(req *http.Request) *WAFRuleResult {
	// Check URL path and raw query
	target := req.URL.Path + "?" + req.URL.RawQuery
	if pathTraversalPattern.MatchString(target) {
		return &WAFRuleResult{
			RuleID:        r.ID(),
			Action:        WAFActionBlock,
			Severity:      maat.SeveritySevere,
			Certainty:     0.95,
			CorrelationID: newCorrelationID(),
		}
	}
	return nil
}

// ─── SEKHEM-005: Invalid UTF-8 in Headers ────────────────────────────────────

type invalidUTF8Rule struct{}

func newInvalidUTF8Rule() WAFRule { return &invalidUTF8Rule{} }

func (r *invalidUTF8Rule) ID() string { return "SEKHEM-005" }

func (r *invalidUTF8Rule) Inspect(req *http.Request) *WAFRuleResult {
	// Check key headers for invalid UTF-8 sequences
	checkHeaders := []string{"User-Agent", "Referer", "Accept", "X-Forwarded-For", "Authorization"}
	for _, name := range checkHeaders {
		val := req.Header.Get(name)
		if val != "" && !utf8.ValidString(val) {
			return &WAFRuleResult{
				RuleID:        r.ID(),
				Action:        WAFActionBlock,
				Severity:      maat.SeverityModerate,
				Certainty:     0.98,
				CorrelationID: newCorrelationID(),
			}
		}
	}
	return nil
}

// ─── SEKHEM-006: Missing or Forged Host Header ───────────────────────────────

// allowedHosts is the set of valid Host values. SEKHEM validates that the Host
// header is present and matches one of the expected values. An empty Host or a
// host not in this set is a sign of a crafted request bypassing DNS/NPM.
//
// Populated from compile-time constants; operator can extend via WithAllowedHosts.
var defaultAllowedHosts = map[string]bool{
	"mcp.souhimbou.ai":       true, // production MCP server (Caddy → khepra-mcp)
	"souhimbou.ai":           true, // main marketing/app domain (Next.js → MCP proxy)
	"www.souhimbou.ai":       true,
	"agent.souhimbou.ai":     true,
	"souhimbou.org":          true,
	"adinkhepra.com":         true,
	"www.adinkhepra.com":     true,
	"souhimbou-ai.fly.dev":   true,  // Fly.io deployment (Next.js proxy target)
	"localhost":               true,
	"localhost:8080":          true,
	"localhost:45444":         true,
	"127.0.0.1":               true,
	"127.0.0.1:8080":          true,
	"127.0.0.1:45444":         true,
}

type invalidHostRule struct {
	allowedHosts map[string]bool
}

func newInvalidHostRule() WAFRule {
	return &invalidHostRule{allowedHosts: defaultAllowedHosts}
}

func (r *invalidHostRule) ID() string { return "SEKHEM-006" }

func (r *invalidHostRule) Inspect(req *http.Request) *WAFRuleResult {
	host := req.Host
	if host == "" {
		host = req.Header.Get("Host")
	}
	if host == "" {
		return &WAFRuleResult{
			RuleID:        r.ID(),
			Action:        WAFActionBlock,
			Severity:      maat.SeverityModerate,
			Certainty:     0.99,
			CorrelationID: newCorrelationID(),
		}
	}
	// Strip port from host for comparison
	hostOnly := host
	if idx := strings.LastIndex(host, ":"); idx != -1 {
		// Keep port if it's part of a known host:port pair
		if !r.allowedHosts[host] {
			hostOnly = host[:idx]
		}
	}
	if !r.allowedHosts[host] && !r.allowedHosts[hostOnly] {
		return &WAFRuleResult{
			RuleID:        r.ID(),
			Action:        WAFActionBlock,
			Severity:      maat.SeverityModerate,
			Certainty:     0.85,
			CorrelationID: newCorrelationID(),
		}
	}
	return nil
}

// ─── SEKHEM-007: Per-IP Rate Limit ───────────────────────────────────────────
// Replaces the standalone RateLimitMiddleware. Uses sync.Map for lock-free
// hot-path reads. Each entry is a *rateBucket protected by its own mutex.

const (
	rateLimitMaxReqs   = 100
	rateLimitWindow    = 1 * time.Minute
	rateLimitCleanup   = 5 * time.Minute
)

type rateBucket struct {
	mu          sync.Mutex
	lastRequest time.Time
	requests    int
}

type rateLimitRule struct {
	buckets sync.Map // map[string]*rateBucket
}

func newRateLimitRule() WAFRule {
	r := &rateLimitRule{}
	// Start background cleanup goroutine
	go func() {
		ticker := time.NewTicker(rateLimitCleanup)
		defer ticker.Stop()
		for range ticker.C {
			cutoff := time.Now().Add(-2 * rateLimitWindow)
			r.buckets.Range(func(key, val any) bool {
				b := val.(*rateBucket)
				b.mu.Lock()
				if b.lastRequest.Before(cutoff) {
					r.buckets.Delete(key)
				}
				b.mu.Unlock()
				return true
			})
		}
	}()
	return r
}

func (r *rateLimitRule) ID() string { return "SEKHEM-007" }

func (r *rateLimitRule) Inspect(req *http.Request) *WAFRuleResult {
	// Extract client IP — use X-Real-IP if behind NPM reverse proxy
	ip := req.Header.Get("X-Real-IP")
	if ip == "" {
		ip = req.RemoteAddr
		if idx := strings.LastIndex(ip, ":"); idx != -1 {
			ip = ip[:idx]
		}
	}

	now := time.Now()

	val, _ := r.buckets.LoadOrStore(ip, &rateBucket{lastRequest: now, requests: 0})
	b := val.(*rateBucket)

	b.mu.Lock()
	defer b.mu.Unlock()

	if now.Sub(b.lastRequest) > rateLimitWindow {
		b.lastRequest = now
		b.requests = 1
		return nil
	}

	b.requests++
	if b.requests > rateLimitMaxReqs {
		return &WAFRuleResult{
			RuleID:        r.ID(),
			Action:        WAFActionChallenge,
			Severity:      maat.SeverityModerate,
			Certainty:     1.0,
			CorrelationID: newCorrelationID(),
		}
	}
	return nil
}

// ─── SEKHEM-008: Malicious User-Agents ───────────────────────────────────────

// maliciousUAPatterns covers known scanner and exploit framework UA strings.
// Additions here do not require a new rule file — extend the slice.
var maliciousUAPatterns = regexp.MustCompile(
	`(?i)(sqlmap|nikto|nmap|masscan|zgrab|nuclei|dirbuster|gobuster` +
		`|wfuzz|hydra|medusa|burpsuite|havij|acunetix|nessus|openvas` +
		`|metasploit|curl\/7\.(?:1[0-9]|[0-6]\d)\.|python-requests\/1\.` +
		`|python-urllib|go-http-client\/1\.0|libwww-perl|lwp-trivial` +
		`|wget\/1\.[01]\.|java\/1\.[456]\.|jakarta commons-httpclient` +
		`|zmeu|morfeus|jaascois|paros|webshag)`)

type maliciousUARule struct{}

func newMaliciousUARule() WAFRule { return &maliciousUARule{} }

func (r *maliciousUARule) ID() string { return "SEKHEM-008" }

func (r *maliciousUARule) Inspect(req *http.Request) *WAFRuleResult {
	ua := req.UserAgent()
	// Empty UA is allowed — server-to-server calls (e.g. Vercel/Next.js proxy,
	// internal health probes, API clients) legitimately omit User-Agent.
	if ua == "" {
		return nil
	}
	if maliciousUAPatterns.MatchString(ua) {
		return &WAFRuleResult{
			RuleID:        r.ID(),
			Action:        WAFActionBlock,
			Severity:      maat.SeveritySevere,
			Certainty:     0.82,
			CorrelationID: newCorrelationID(),
		}
	}
	return nil
}

// ─── helpers ──────────────────────────────────────────────────────────────────

// scanString checks the URL (path + query) and all header values against pattern.
// It does NOT read the body — body scanning would require buffering which is
// handled by the WAFShield GinHandler before the rule loop.
func scanString(req *http.Request, pattern *regexp.Regexp) bool {
	// URL path + raw query
	target := req.URL.Path + "?" + req.URL.RawQuery
	if pattern.MatchString(target) {
		return true
	}

	// All header values
	for _, vals := range req.Header {
		for _, v := range vals {
			if pattern.MatchString(v) {
				return true
			}
		}
	}

	// Body peek — the body has already been buffered and can be re-read.
	if req.Body != nil {
		// Limit body scan to 64 KiB to avoid excessive allocations on large uploads.
		bodyBytes, err := io.ReadAll(io.LimitReader(req.Body, 64*1024))
		if err == nil && len(bodyBytes) > 0 {
			if pattern.MatchString(string(bodyBytes)) {
				// Rewind body for downstream handlers
				req.Body = io.NopCloser(strings.NewReader(string(bodyBytes)))
				return true
			}
			// Rewind body for downstream handlers even on no-match
			req.Body = io.NopCloser(strings.NewReader(string(bodyBytes)))
		}
	}

	return false
}
