package audit

import (
	"fmt"
	"strings"
	"time"
)

// GenerateAFFiNE creates a markdown report optimized for AFFiNE block editor.
func GenerateAFFiNE(r *RiskReport) string {
	var sb strings.Builder

	// Header Block
	sb.WriteString(fmt.Sprintf("# Executive Decision Memo: %s\n\n", r.Client))
	sb.WriteString(fmt.Sprintf("**Date:** %s  \n", time.Now().Format("2006-01-02")))
	sb.WriteString(fmt.Sprintf("**Scan ID:** `%s`  \n", r.ScanID))
	sb.WriteString("**Classification:** CONFIDENTIAL // PROPRIETARY\n\n")

	// 1. Executive Summary
	sb.WriteString("## 1. Executive Summary\n\n")
	sb.WriteString("This diagnostic assessment utilized the **Khepra Protocol** to evaluate the architectural integrity, security posture, and compliance readiness of the target environment. ")
	sb.WriteString("The analysis was conducted against **NIST 800-171** and **DoD STIG** baselines.\n\n")

	criticalCount := 0
	highCount := 0
	for _, risk := range r.Risks {
		if risk.Severity == "CRITICAL" {
			criticalCount++
		}
		if risk.Severity == "HIGH" {
			highCount++
		}
	}

	sb.WriteString("### Risk Posture At-A-Glance\n")
	sb.WriteString(fmt.Sprintf("- **CRITICAL Vulnerabilities:** %d\n", criticalCount))
	sb.WriteString(fmt.Sprintf("- **HIGH Severity Risks:** %d\n", highCount))
	sb.WriteString(fmt.Sprintf("- **Total Findings:** %d\n\n", len(r.Risks)))

	if criticalCount > 0 {
		sb.WriteString("> ⚠️ **IMMEDIATE ACTION REQUIRED:** Critical vulnerabilities detected that pose an existential threat to data sovereignty or system availability.\n\n")
	}

	// 2. Strategic Findings (Top 5)
	sb.WriteString("## 2. Strategic Findings & Analysis\n\n")

	limit := 5
	if len(r.Risks) < 5 {
		limit = len(r.Risks)
	}

	for i := 0; i < limit; i++ {
		risk := r.Risks[i]
		sb.WriteString(fmt.Sprintf("### %d. %s [%s]\n", i+1, risk.Title, risk.Severity))
		sb.WriteString(fmt.Sprintf("**Observation:** %s\n\n", risk.Description))
		sb.WriteString(fmt.Sprintf("**Operational Impact:** Violates `%s` baseline controls.\n\n", risk.STIGReference))
		sb.WriteString(fmt.Sprintf("**Recommendation:** %s\n\n", risk.Remediation))
		sb.WriteString("---\n\n")
	}

	// 3. PQC Readiness (The "Future Proof" section)
	sb.WriteString("## 3. Quantum Readiness (PQC) Assessment\n\n")
	sb.WriteString("Analysis of the cryptographic posture indicates reliance on legacy primitives (RSA/ECDSA). \n")
	sb.WriteString("- **Agility Score:** 0.0/10.0\n")
	sb.WriteString("- **Evaluation:** The architecture is currently vulnerable to Store-Now-Decrypt-Later (SNDL) attacks.\n")
	sb.WriteString("- **Recommendation:** Begin migration to **Dilithium-Mode3** for identity assertions.\n\n")

	// 4. Next Steps
	sb.WriteString("## 4. Required Decisions\n\n")
	sb.WriteString("1. **Authorize Remediation Sprint:** Address the Critical/High findings immediately.\n")
	sb.WriteString("2. **Implement Continuous Monitoring:** Deploy Khepra Sonar Agents for real-time drift detection.\n")
	sb.WriteString("3. **Authorize PQC Upgrade:** Schedule cryptographic migration planning.\n\n")

	sb.WriteString("*Generated by Khepra Agentic Security Auditor (KASA)*")

	return sb.String()
}
