package audit

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/arsenal"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/connectors"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/dag"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/scanner"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/stigs"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/zscan"
)

// RiskReport is the output generated by Khepra after analyzing a Sonar Snapshot.
type RiskReport struct {
	Client   string      `json:"client"`
	ScanID   string      `json:"scan_id"`
	Risks    []RiskItem  `json:"risks"`
	TrustMap *dag.Memory `json:"trust_map_snapshot"` // The constructed DAG
}

type RiskItem struct {
	Severity      string `json:"severity"` // CRITICAL, HIGH, MEDIUM
	Title         string `json:"title"`
	Description   string `json:"description"`
	Remediation   string `json:"remediation"`
	CausalLink    string `json:"causal_link_id"`
	STIGReference string `json:"stig_ref,omitempty"` // ID of the crossed STIG
}

// Ingest processing a Sonar snapshot and generates a Risk Report.
func Ingest(snapshotPath, gitleaksPath, zscanPath, trufflePath, zapPath, retirePath, sarifPath, detectPath, scapPath, checklistPath, nessusPath, kubePath, crawlerPath string) (*RiskReport, error) {
	data, err := os.ReadFile(snapshotPath)
	if err != nil {
		return nil, err
	}

	var snap AuditSnapshot
	if err := json.Unmarshal(data, &snap); err != nil {
		return nil, fmt.Errorf("invalid snapshot format: %v", err)
	}

	// [KHEPRA INTELLIGENCE] Load STIG Library
	// Use map for fast lookup
	stigMap := make(map[string]stigs.STIGItem)
	if items, err := stigs.LoadLibrary("docs/STIG_to_NIST171_Mapping_Ultimate.xlsx"); err == nil {
		for _, it := range items {
			stigMap[it.ID] = it
		}
		fmt.Printf("[KHEPRA] Applied Military Intelligence: %d STIG Controls loaded for analysis.\n", len(items))
	} else {
		fmt.Printf("[KHEPRA] Warning: STIG Library not found. Running in civilian heuristics mode.\n")
	}

	// Initialize the Attestation DAG
	d := dag.NewMemory()

	// Create Root Node (The Host)
	hostNodeID := "asset:host:" + snap.Host.Hostname
	d.Add(&dag.Node{
		ID:     hostNodeID,
		Action: "Host Discovery",
		Symbol: "Asase Yaa (Earth)",
		Time:   snap.Timestamp.Format(time.RFC3339),
	}, nil)

	risks := []RiskItem{}

	// Helper to link finding to STIG
	linkToSTIG := func(tool, toolID, _ /*description*/, nodeID string, _ /*severity*/ string) string {
		stigID, cci := stigs.MapToSTIG(tool, toolID)

		// Create/Link STIG Control Node
		controlNodeID := "stig:control:" + stigID

		d.Add(&dag.Node{
			ID:     controlNodeID,
			Action: "STIG Control Check",
			Symbol: "Hwe Mu Dua (Measure)",
			Time:   time.Now().Format(time.RFC3339),
			PQC:    map[string]string{"stig_id": stigID, "cci": cci},
		}, []string{nodeID}) // Finding -> Control

		return stigID
	}

	// 1. [EVIDENCE] ZScan
	if zscanPath != "" {
		fmt.Printf("[KHEPRA STIG-BUS] Ingesting Network Evidence: %s\n", zscanPath)
		zresults, err := zscan.ParseZGrabFile(zscanPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse ZScan artifact: %v\n", err)
		} else {
			fmt.Printf("[KHEPRA] ZScan loaded %d host records.\n", len(zresults))
			for _, res := range zresults {
				// Match against our host IP or just generic intel
				if res.IP == snap.Host.PublicIP || snap.Host.PublicIP == "" {
					nodeID := "evidence:zscan:" + res.IP

					// [PQC] Metadata Enrichment
					pqcMeta := map[string]string{
						"crypto_agility": "unknown", // Default
						"cipher_suite":   "unknown",
						"source":         "zscan_passive",
					}

					if res.Data.TLS.Status == "success" {
						cs := res.Data.TLS.Result.HandshakeLog.ServerHello.CipherSuite.Name
						pqcMeta["cipher_suite"] = cs
						if strings.Contains(cs, "RSA") || strings.Contains(cs, "ECDH") {
							pqcMeta["crypto_agility"] = "legacy_vulnerable"
						} else if strings.Contains(cs, "KYBER") || strings.Contains(cs, "DILITHIUM") {
							pqcMeta["crypto_agility"] = "quantum_safe"
						}
					}

					d.Add(&dag.Node{
						ID:     nodeID,
						Action: "Network Port Evidence",
						Symbol: "Hwe Mu Dua (Examination)",
						Time:   time.Now().Format(time.RFC3339),
						PQC:    pqcMeta,
					}, []string{hostNodeID})

					// TLS Analysis
					if res.Data.TLS.Status == "success" {
						params := res.Data.TLS.Result.HandshakeLog.ServerHello
						if strings.Contains(params.CipherSuite.Name, "RSA") || strings.Contains(params.CipherSuite.Name, "ECDH") {
							// Risk
							stigRef := linkToSTIG("zscan", "cipher-algo", "Weak Cipher", nodeID, "MEDIUM")
							risks = append(risks, RiskItem{
								Severity: "MEDIUM", Title: "Quantum-Vulnerable Handshake (ZScan)",
								Description: fmt.Sprintf("Detected %s using %s. Susceptible to Harvest-Now-Decrypt-Later.", params.Version.Name, params.CipherSuite.Name),
								Remediation: "Plan Migration to Kyber-1024 or similar KEM.",
								CausalLink:  nodeID, STIGReference: stigRef,
							})
						}
					}
				}
			}
		}
	}

	// [ARSENAL] Gitleaks / Secret Hunter
	if gitleaksPath != "" {
		fmt.Printf("[KHEPRA] Processing Interna Leakage via Gitleaks: %s\n", gitleaksPath)
		leaks, err := arsenal.ParseGitleaks(gitleaksPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse Gitleaks report: %v\n", err)
		} else {
			for _, leak := range leaks {
				nodeID := fmt.Sprintf("evidence:leak:%s:%d", leak.File, leak.StartLine)
				d.Add(&dag.Node{
					ID:     nodeID,
					Action: "Secret Artifact",
					Symbol: "Kuntinkantan (Hidden Wisdom/Secrets)", // Ironic usage
					Time:   time.Now().Format(time.RFC3339),
				}, []string{hostNodeID})

				stigRef := linkToSTIG("gitleaks", leak.Description, leak.Match, nodeID, "CRITICAL")
				risks = append(risks, RiskItem{
					Severity: "CRITICAL", Title: "Hardcoded Secret Detected (Gitleaks)",
					Description: fmt.Sprintf("Secret leaked in %s (Line %d). Rule: %s. Author: %s", leak.File, leak.StartLine, leak.Description, leak.Author),
					Remediation: "Rotate secret IMMEDIATELY. Revoke prior commits. Ref: STIG IA-5 (Authenticator Management).",
					CausalLink:  nodeID, STIGReference: stigRef,
				})
			}
			fmt.Printf("[KHEPRA] Identified %d confirmed secret leaks.\n", len(leaks))
		}
	}

	// [ARSENAL] TruffleHog (Big Brother Mode)
	if trufflePath != "" {
		fmt.Printf("[KHEPRA] Processing Deep Secret Scan via TruffleHog: %s\n", trufflePath)
		findings, err := arsenal.ParseTruffleHog(trufflePath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse TruffleHog report: %v\n", err)
		} else {
			for i, f := range findings {
				// Use SourceID or index for unique ID if SourceMetadata is absent
				fname := f.SourceMetadata.Data.Filesystem.File
				if fname == "" {
					fname = f.SourceMetadata.Data.Git.File
				}
				if fname == "" {
					fname = "unknown_source"
				}

				nodeID := fmt.Sprintf("evidence:truffle:%s:%s:%d", f.DetectorName, fname, i)
				d.Add(&dag.Node{
					ID:     nodeID,
					Action: "High Entropy Artifact",
					Symbol: "Fawohodie (Independence/Freedom - Revocation)",
					Time:   time.Now().Format(time.RFC3339),
					PQC: map[string]string{
						"verified": fmt.Sprintf("%v", f.Verified),
						"detector": f.DetectorName,
					},
				}, []string{hostNodeID})

				stigRef := linkToSTIG("trufflehog", f.DetectorName, f.Raw, nodeID, "CRITICAL")
				risks = append(risks, RiskItem{
					Severity: "CRITICAL", Title: fmt.Sprintf("Verified Secret Detected (%s)", f.DetectorName),
					Description: fmt.Sprintf("TruffleHog found a %s secret in %s. Verified: %v.", f.DetectorName, fname, f.Verified),
					Remediation: "Immediate Rotation Required. Check process ENV vars.",
					CausalLink:  nodeID, STIGReference: stigRef,
				})
			}
			fmt.Printf("[KHEPRA] Deep Scan identified %d items.\n", len(findings))
		}
	}

	// [ARSENAL] ZAP (DAST)
	if zapPath != "" {
		fmt.Printf("[KHEPRA] Processing OWASP ZAP DAST Report: %s\n", zapPath)
		report, err := arsenal.ParseZAP(zapPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse ZAP report: %v\n", err)
		} else {
			for _, site := range report.Site {
				for _, alert := range site.Alerts {
					// Filter for Risk Code 3 (High) and 2 (Medium)
					if alert.RiskCode == "3" || alert.RiskCode == "2" {
						nodeID := fmt.Sprintf("evidence:zap:%s", alert.PluginID)
						d.Add(&dag.Node{
							ID:     nodeID,
							Action: "DAST Artifact",
							Symbol: "Owo Foro Adobe (Prudence/Diligence)",
							Time:   time.Now().Format(time.RFC3339),
							PQC:    map[string]string{"tool": "ZAP", "risk": alert.RiskCode},
						}, []string{hostNodeID})

						stigRef := linkToSTIG("zap", alert.PluginID, alert.Desc, nodeID, "HIGH")
						risks = append(risks, RiskItem{
							Severity: "HIGH", Title: fmt.Sprintf("DAST: %s", alert.Alert),
							Description: alert.Desc, Remediation: alert.Solution,
							CausalLink: nodeID, STIGReference: stigRef,
						})
					}
				}
			}
		}
	}

	// [ARSENAL] Retire.js (Supply Chain)
	if retirePath != "" {
		fmt.Printf("[KHEPRA] Processing Retire.js Supply Chain Report: %s\n", retirePath)
		findings, err := arsenal.ParseRetireJS(retirePath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse Retire.js report: %v\n", err)
		} else {
			for _, f := range findings {
				for _, res := range f.Results {
					if res.Level == "high" || res.Level == "critical" {
						nodeID := fmt.Sprintf("evidence:retire:%s", res.Component)
						d.Add(&dag.Node{
							ID:     nodeID,
							Action: "Supply Chain Artifact",
							Symbol: "Funtunfunefu (Shared Stomach/Dependency)",
							Time:   time.Now().Format(time.RFC3339),
							PQC:    map[string]string{"component": res.Component, "version": res.Version},
						}, []string{hostNodeID})

						stigRef := linkToSTIG("retirejs", res.Component, res.Version, nodeID, "HIGH")
						risks = append(risks, RiskItem{
							Severity: "HIGH", Title: fmt.Sprintf("Vulnerable Component: %s", res.Component),
							Description: fmt.Sprintf("Found in %s. Version %s is vulnerable.", f.File, res.Version),
							Remediation: "Upgrade library immediately. Check 'npm audit'.",
							CausalLink:  nodeID, STIGReference: stigRef,
						})
					}
				}
			}
		}
	}

	// [ARSENAL] SARIF (MegaLinter/SpotBugs/CI Fuzz)
	if sarifPath != "" {
		fmt.Printf("[KHEPRA] Processing Universal SARIF Report: %s\n", sarifPath)
		report, err := arsenal.ParseSARIF(sarifPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse SARIF report: %v\n", err)
		} else {
			for _, run := range report.Runs {
				toolName := run.Tool.Driver.Name
				for _, res := range run.Results {
					if res.Level == "error" || res.Level == "warning" {
						// Extract location
						loc := "unknown"
						if len(res.Locations) > 0 {
							loc = fmt.Sprintf("%s:%d", res.Locations[0].PhysicalLocation.ArtifactLocation.Uri, res.Locations[0].PhysicalLocation.Region.StartLine)
						}

						nodeID := fmt.Sprintf("evidence:sarif:%s:%s", toolName, res.RuleId)
						d.Add(&dag.Node{
							ID:     nodeID,
							Action: "SAST Artifact",
							Symbol: "Hwe Mu Dua (Examination)",
							Time:   time.Now().Format(time.RFC3339),
							PQC:    map[string]string{"tool": toolName, "rule": res.RuleId},
						}, []string{hostNodeID})

						sev := "MEDIUM"
						if res.Level == "error" {
							sev = "HIGH"
						}

						stigRef := linkToSTIG("sarif", res.RuleId, res.Message.Text, nodeID, "MEDIUM")
						risks = append(risks, RiskItem{
							Severity: sev, Title: fmt.Sprintf("SAST (%s): %s", toolName, res.RuleId),
							Description: fmt.Sprintf("%s at %s.", res.Message.Text, loc),
							Remediation: "Review code snippet.",
							CausalLink:  nodeID, STIGReference: stigRef,
						})
					}
				}
			}
		}
	}

	// [ARSENAL] Detect-Secrets (Yelp)
	if detectPath != "" {
		fmt.Printf("[KHEPRA] Processing Detect-Secrets Report: %s\n", detectPath)
		results, err := arsenal.ParseDetectSecrets(detectPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse detect-secrets report: %v\n", err)
		} else {
			count := 0
			for file, findings := range results {
				for i, f := range findings {
					count++
					nodeID := fmt.Sprintf("evidence:ds:%s:%d", file, i)
					d.Add(&dag.Node{
						ID:     nodeID,
						Action: "Secret Keyword Artifact",
						Symbol: "Kuntinkantan (Hidden Wisdom/Secrets)",
						Time:   time.Now().Format(time.RFC3339),
						PQC:    map[string]string{"type": f.Type, "algo": "detect-secrets"},
					}, []string{hostNodeID})

					stigRef := linkToSTIG("detect-secrets", f.Type, f.HashedSecret, nodeID, "HIGH")
					risks = append(risks, RiskItem{
						Severity: "HIGH", Title: fmt.Sprintf("Secret Suspect: %s", f.Type),
						Description: fmt.Sprintf("Found in %s (Line %d).", file, f.LineNumber),
						Remediation: "Verify variable naming and content. Mark false positives in baseline.",
						CausalLink:  nodeID, STIGReference: stigRef,
					})
				}
			}
			fmt.Printf("[KHEPRA] Detect-Secrets flagged %d items.\n", count)
		}
	}

	// [STIG] SCAP (XCCDF)
	if scapPath != "" {
		fmt.Printf("[KHEPRA STIG-BUS] Ingesting OpenSCAP XCCDF: %s\n", scapPath)
		results, err := connectors.ParseXCCDF(scapPath)
		if err == nil {
			for _, r := range results {
				if r.Result == "fail" {
					nodeID := fmt.Sprintf("evidence:scap:%s", r.IDRef)
					d.Add(&dag.Node{ID: nodeID, Action: "SCAP Fail", Symbol: "Fawohodie", Time: time.Now().Format(time.RFC3339)}, []string{hostNodeID})

					stigRef := linkToSTIG("scap", r.IDRef, "Rule Failed", nodeID, "HIGH")
					risks = append(risks, RiskItem{
						Severity: "HIGH", Title: "Compliance Fail: " + r.IDRef,
						Description: "Automated XCCDF check failed.", Remediation: "Run remediation script.",
						CausalLink: nodeID, STIGReference: stigRef,
					})
				}
			}
		}
	}

	// [STIG] Checklist (.ckl)
	if checklistPath != "" {
		fmt.Printf("[KHEPRA STIG-BUS] Ingesting DISA Checklist: %s\n", checklistPath)
		vulns, err := connectors.ParseCKL(checklistPath)
		if err == nil {
			for _, v := range vulns {
				nodeID := fmt.Sprintf("evidence:ckl:%s", v.FindingID)
				d.Add(&dag.Node{ID: nodeID, Action: "Checklist Open", Symbol: "Fawohodie", Time: time.Now().Format(time.RFC3339)}, []string{hostNodeID})

				// CKL usually has direct STIG IDs in attributes, simplistic map here
				stigRef := linkToSTIG("checklist", v.FindingID, v.Comments, nodeID, "MEDIUM")
				risks = append(risks, RiskItem{
					Severity: "MEDIUM", Title: "Manual Finding: " + v.FindingID,
					Description: v.Comments, Remediation: "See Comments.",
					CausalLink: nodeID, STIGReference: stigRef,
				})
			}
		}
	}

	// [STIG] Nessus / ACAS
	if nessusPath != "" {
		fmt.Printf("[KHEPRA STIG-BUS] Ingesting Nessus/ACAS Scan: %s\n", nessusPath)
		items, err := connectors.ParseNessus(nessusPath)
		if err == nil {
			for _, i := range items {
				// Focus on compliance failures
				isFail := i.Severity == "3" || i.Severity == "4" || strings.Contains(i.Compliance, "FAILED")
				if isFail {
					nodeID := fmt.Sprintf("evidence:nessus:%s", i.PluginID)
					d.Add(&dag.Node{ID: nodeID, Action: "ACAS Vulnerability", Symbol: "Funtunfunefu", Time: time.Now().Format(time.RFC3339)}, []string{hostNodeID})

					stigRef := linkToSTIG("nessus", i.PluginID, i.Description, nodeID, "HIGH")
					risks = append(risks, RiskItem{
						Severity: "HIGH", Title: "ACAS: " + i.PluginName,
						Description: i.Description, Remediation: "Patch/Config.",
						CausalLink: nodeID, STIGReference: stigRef,
					})
				}
			}
		}
	}

	// [STIG] Kubernetes (Kube-Bench)
	if kubePath != "" {
		fmt.Printf("[KHEPRA STIG-BUS] Ingesting Kube-Bench: %s\n", kubePath)
		fails, err := connectors.ParseKubeBench(kubePath)
		if err == nil {
			for _, f := range fails {
				nodeID := fmt.Sprintf("evidence:k8s:%s", f.TestNumber)
				d.Add(&dag.Node{ID: nodeID, Action: "K8s Misconfig", Symbol: "Fawohodie", Time: time.Now().Format(time.RFC3339)}, []string{hostNodeID})

				stigRef := linkToSTIG("kube-bench", f.TestNumber, f.TestDesc, nodeID, "HIGH")
				risks = append(risks, RiskItem{
					Severity: "HIGH", Title: "CIS K8s: " + f.TestDesc,
					Description: f.Audit, Remediation: f.ActualValue,
					CausalLink: nodeID, STIGReference: stigRef,
				})
			}
		}
	}

	// [INTELLIGENCE] Crawler (SpiderFoot)
	if crawlerPath != "" {
		fmt.Printf("[KHEPRA] Processing Deep SpiderFoot Intelligence: %s\n", crawlerPath)
		findings, err := scanner.ParseCrawler(crawlerPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse Crawler Intel: %v\n", err)
		} else {
			fmt.Printf("[KHEPRA] Crawler returned %d data points.\n", len(findings))
			for i, f := range findings {
				// We map "Internal" or "Sensitive" findings to Risks
				// This requires heuristic filtering, otherwise it's too noisy.
				isRisky := false
				severity := "INFO"

				if strings.Contains(f.Type, "VULNERABILITY") || strings.Contains(f.Data, "exposed") {
					isRisky = true
					severity = "HIGH"
				} else if strings.Contains(f.Type, "LEAK") || strings.Contains(f.Type, "PASSWORD") {
					isRisky = true
					severity = "CRITICAL"
				}

				if isRisky {
					nodeID := fmt.Sprintf("intel:crawler:%d", i)
					d.Add(&dag.Node{
						ID:     nodeID,
						Action: "OSINT Artifact",
						Symbol: "Hwe Mu Dua",
						Time:   time.Now().Format(time.RFC3339),
						PQC:    map[string]string{"type": f.Type, "module": f.Module},
					}, []string{hostNodeID})

					stigRef := linkToSTIG("crawler", f.Type, f.Data, nodeID, severity)
					risks = append(risks, RiskItem{
						Severity: severity, Title: "OSINT: " + f.Type,
						Description: fmt.Sprintf("Found %s via %s. Data: %s", f.Type, f.Module, f.Data),
						Remediation: "Investigate exposure.",
						CausalLink:  nodeID, STIGReference: stigRef,
					})
				}
			}
		}
	}

	// Analyze Manifests (Supply Chain Risk)
	for _, m := range snap.Manifests {
		nodeID := "asset:file:" + m.Type + ":" + m.Checksum[:8]
		d.Add(&dag.Node{
			ID:     nodeID,
			Action: "Dependency Check",
			Symbol: "Funtunfunefu (Shared Stomach/Dependency)",
			Time:   time.Now().Format(time.RFC3339),
		}, []string{hostNodeID})

		if m.Type == "npm" {
			// Find relevant STIG (Heuristic Match)
			stigRef := "GEN-000000"
			stigTitle := "Unpinned Dependency"

			// Simple heuristic to find a Configuration Management STIG
			for _, s := range stigMap {
				if s.Family == "Configuration Management" && strings.Contains(s.Title, "software") {
					stigRef = s.ID
					stigTitle = s.Title
					break
				}
			}

			risks = append(risks, RiskItem{
				Severity:      "HIGH",
				Title:         "Unpinned NPM Dependency Tree",
				Description:   fmt.Sprintf("Manifest found at %s. Violation of CM protocol.", m.Path),
				Remediation:   "Evaluate against " + stigTitle,
				CausalLink:    nodeID,
				STIGReference: stigRef,
			})
		}
	}

	report := &RiskReport{
		Client:   snap.Host.Hostname,
		ScanID:   snap.ScanID,
		Risks:    risks,
		TrustMap: d,
	}

	return report, nil
}

// SaveReport writes the report to disk
func SaveReport(r *RiskReport, path string) error {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}
