package evidence

// builder.go — C3PAO evidence package builder and ZIP writer.
//
// Usage:
//
//	pkg, err := evidence.Build(evidence.BuildConfig{
//	    Findings: findings,
//	    DAGNodes: dagNodes,
//	    Target:   "http://target:8080",
//	    OutputDir: ".",
//	})
//
// The result pkg.ZipPath points to the written ZIP file.
// manifest.json lists the SHA-256 of every artifact and, when a key is
// configured, is signed with ML-DSA-87 (FIPS 204) via the adinkra package.

import (
	"archive/zip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"time"

	"github.com/nouchix/PQC-Khepra-MCP/pkg/adinkra"
	"golang.org/x/crypto/sha3"
)

// Build constructs the C3PAOPackage and writes all 13 artifacts into a ZIP file.
// It returns the populated C3PAOPackage (with ZipPath set) or an error.
func Build(cfg BuildConfig) (*C3PAOPackage, error) {
	if len(cfg.Findings) == 0 {
		return nil, fmt.Errorf("evidence.Build: at least one finding is required")
	}

	// Defaults
	if cfg.Framework == "" {
		cfg.Framework = "CMMC Level 2 / NIST SP 800-171 Rev2"
	}
	if cfg.OutputDir == "" {
		cfg.OutputDir = "."
	}
	if cfg.Target == "" {
		cfg.Target = "unknown"
	}

	// Populate package
	pkg := &C3PAOPackage{
		PackageID:    fmt.Sprintf("khepra-%d", time.Now().UnixMilli()),
		Generated:    time.Now().UTC(),
		Target:       cfg.Target,
		Framework:    cfg.Framework,
		Findings:     cfg.Findings,
		DAGNodes:     cfg.DAGNodes,
		FlightFrames: cfg.FlightFrames,
		Assets:       cfg.Assets,
		ESPs:         cfg.ESPs,
		Personnel:    cfg.Personnel,
		TrainingRecords: cfg.TrainingRecords,
	}

	// SPRS score
	pkg.SPRS = CalculateSPRS(cfg.Findings)

	// Financial totals
	for _, f := range cfg.Findings {
		pkg.TotalExposure += f.ExposureUSD
		pkg.RemediationCost += f.RemediationUSD
	}
	if pkg.RemediationCost > 0 {
		pkg.ROI = int(pkg.TotalExposure / pkg.RemediationCost)
	}

	// Integrity: manifest.json lists the SHA-256 of every file and is signed
	// with ML-DSA-87 when a key is configured. Inline signature fields point
	// to that signature; inline hashes are real SHA-256 digests of the data.
	sigFn := signerFunc(cfg.PrivKey, cfg.PubKey)
	hashFn := hashOf

	// Generate all 13 artifacts
	artifacts := generateAll(pkg, sigFn, hashFn)

	// Write manifest
	manifestSig, manifestBytes, err := buildManifest(pkg, artifacts, cfg.PrivKey, cfg.PubKey)
	if err != nil {
		return nil, fmt.Errorf("evidence.Build: manifest: %w", err)
	}
	pkg.ManifestSignature = manifestSig
	artifacts = append(artifacts, artifact{Name: "manifest.json", Content: manifestBytes})
	pkg.ArtifactCount = len(artifacts)

	// Write ZIP
	zipName := fmt.Sprintf("%s-c3pao-evidence.zip", pkg.PackageID)
	zipPath := filepath.Join(cfg.OutputDir, zipName)
	if err := writeZIP(zipPath, pkg.PackageID, artifacts); err != nil {
		return nil, fmt.Errorf("evidence.Build: zip: %w", err)
	}
	pkg.ZipPath = zipPath

	return pkg, nil
}

// ─── Manifest ─────────────────────────────────────────────────────────────────

func buildManifest(pkg *C3PAOPackage, arts []artifact, privKey, pubKey []byte) (string, []byte, error) {
	type fileEntry struct {
		Name   string `json:"file"`
		SHA256 string `json:"sha256"`
	}
	type manifestOut struct {
		PackageID     string      `json:"package_id"`
		Generated     time.Time   `json:"generated_at"`
		Tool          string      `json:"tool"`
		Patent        string      `json:"patent"`
		Algorithm     string      `json:"algorithm"`
		Target        string      `json:"target"`
		Framework     string      `json:"framework"`
		SPRSScore     int         `json:"sprs_score"`
		ArtifactCount int         `json:"artifact_count"`
		DAGNodes      int         `json:"dag_nodes"`
		FlightFrames  int         `json:"flight_frames"`
		FindingsCount int         `json:"findings_count"`
		Files         []fileEntry `json:"files"`
		C3PAOStatement string    `json:"c3pao_statement"`
		ManifSig      string      `json:"manifest_signature"`
	}

	files := make([]fileEntry, len(arts))
	for i, a := range arts {
		h := sha256.Sum256(a.Content)
		files[i] = fileEntry{
			Name:   a.Name,
			SHA256: hex.EncodeToString(h[:]),
		}
	}

	sig := unsignedNote
	algorithm := "none (package is unsigned)"
	statement := "This evidence package was generated by KHEPRA ERT v2.0. It is UNSIGNED: no signing key was configured, so file integrity rests only on the SHA-256 digests listed below."
	if len(privKey) > 0 {
		// Build signing payload = SHA3-256 over concatenated SHA256 hashes
		h := sha3.New256()
		for _, f := range files {
			h.Write([]byte(f.SHA256))
		}
		payload := h.Sum(nil)
		rawSig, err := adinkra.Sign(privKey, payload)
		if err != nil {
			return "", nil, err
		}
		sig = "ML-DSA-87:" + hex.EncodeToString(rawSig)
		algorithm = "ML-DSA-87 / FIPS 204 (Go crypto/mldsa)"
		statement = "This evidence package was generated by KHEPRA ERT v2.0. manifest.json lists the SHA-256 digest of every file and is signed with ML-DSA-87 (FIPS 204); verifying that signature and the digests verifies every file in the package."
	}

	m := manifestOut{
		PackageID:     pkg.PackageID,
		Generated:     pkg.Generated,
		Tool:          "KHEPRA ERT v2.0 — NouchiX / SecRed Knowledge Inc.",
		Patent:        "U.S. App. No. 63/942,886",
		Algorithm:     algorithm,
		Target:        pkg.Target,
		Framework:     pkg.Framework,
		SPRSScore:     pkg.SPRS.Score,
		ArtifactCount: len(arts) + 1, // +1 for manifest itself
		DAGNodes:      len(pkg.DAGNodes),
		FlightFrames:  len(pkg.FlightFrames),
		FindingsCount: len(pkg.Findings),
		Files:         files,
		C3PAOStatement: statement,
		ManifSig:      sig,
	}

	b, err := json.MarshalIndent(m, "", "  ")
	return sig, b, err
}

// ─── ZIP writer ───────────────────────────────────────────────────────────────

func writeZIP(zipPath, folder string, arts []artifact) error {
	if err := os.MkdirAll(filepath.Dir(zipPath), 0o755); err != nil {
		return err
	}

	f, err := os.Create(zipPath)
	if err != nil {
		return err
	}
	defer f.Close()

	zw := zip.NewWriter(f)
	defer zw.Close()

	for _, a := range arts {
		w, err := zw.Create(path.Join(folder, a.Name)) // zip names always use '/'
		if err != nil {
			return err
		}
		if _, err = w.Write(a.Content); err != nil {
			return err
		}
	}
	return nil
}

// ─── Signing helpers ──────────────────────────────────────────────────────────

// unsignedNote marks evidence produced without a signing key.
const unsignedNote = "UNSIGNED (no signing key configured)"

// signerFunc returns the text placed in per-file signature fields. Files are
// not signed individually: manifest.json signs the SHA-256 of every file, so
// with a key each field points there, and without one it says UNSIGNED.
func signerFunc(privKey, pubKey []byte) func() string {
	if len(privKey) > 0 {
		return func() string {
			return "covered by the ML-DSA-87 signature in manifest.json (SHA-256 of this file)"
		}
	}
	return func() string { return unsignedNote }
}

// hashOf returns "sha256:<hex>" of the JSON encoding of v.
func hashOf(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return "unhashable"
	}
	sum := sha256.Sum256(b)
	return "sha256:" + hex.EncodeToString(sum[:])
}
