// pkg/asaf/policy/compiler.go — ASAF Policy Declaration Language (APDL) Compiler
//
// Parses the human-readable APDL syntax generated by the Compliance Graph UI,
// validates metadata, generates the Ansible playbook YAML, and produces an
// ML-DSA-65 signed execution bundle that the ASAF System Daemon will accept.
//
// APDL syntax (reference):
//
//	@symbol(Eban)            // Adinkra symbol — controls daemon authorization
//	@framework(CMMC.L2)      // compliance framework reference
//	@tier(Sovereign)         // deployment tier
//	@gate(human)             // approval gate (always human for destructive ops)
//
//	control AC-2 {
//	  require: pam_faillock
//	  deny = 3
//	  unlock_time = 900
//	  maps: CMMC.AC.L2-3.1.2, NIST.AC-2, CCI-000048
//	}
//
// The compiler does NOT execute anything — it produces a signed bundle that
// must be submitted to the ASAF System Daemon via the staging workflow.
//
// IP: SecRed Knowledge Inc. / SOUHIMBOU DOH KONE LLC — USPTO #73565085

package policy

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/nouchix/PQC-Khepra-MCP/pkg/adinkra"
)

// validSymbols are the authorized Adinkra symbols in APDL.
// Any other symbol in @symbol() causes compilation to fail.
var validSymbols = map[string]bool{
	"Eban":       true, // fortress — kernel/security ops
	"Nkyinkyim":  true, // adaptability — service/file ops
	"Dwennimmen": true, // strength — user management
	"Fawohodie":  true, // freedom — package management
}

// CompiledPolicy is the output of the APDL compiler.
// It is JSON-serializable for transport to the ASAF System Daemon.
type CompiledPolicy struct {
	// Metadata from @directives
	Symbol    string `json:"symbol"`
	Framework string `json:"framework"`
	Tier      string `json:"tier"`
	Gate      string `json:"gate"`
	ControlID string `json:"control_id"`

	// Parsed requirements (what must be true after remediation)
	Requirements map[string]string `json:"requirements"`

	// Compliance mappings (from 'maps:' directive)
	Mappings []string `json:"mappings"`

	// Generated Ansible YAML playbook
	AnsibleYAML string `json:"ansible_yaml"`

	// Command sequence submitted to asaf-daemon
	Commands [][]string `json:"commands"`

	// Attestation
	CompiledAt string `json:"compiled_at"`
	SourceHash string `json:"source_hash"` // SHA-256 of original APDL source
	Signature  []byte `json:"signature"`   // ML-DSA-65 over canonical bundle bytes
}

// Compile parses APDL source and returns a signed CompiledPolicy.
// privKey is the ASAF agent's ML-DSA-65 private key.
// Pass nil privKey for unsigned bundles (testing only — daemon will reject these).
func Compile(source string, privKey []byte) (*CompiledPolicy, error) {
	cp := &CompiledPolicy{
		Requirements: make(map[string]string),
		CompiledAt:   time.Now().UTC().Format(time.RFC3339),
	}

	// ── 1. EXTRACT @DIRECTIVES ────────────────────────────────────────────────
	if err := extractDirectives(source, cp); err != nil {
		return nil, fmt.Errorf("apdl: directive parse error: %w", err)
	}

	// ── 2. VALIDATE SYMBOL ────────────────────────────────────────────────────
	if cp.Symbol == "" {
		return nil, fmt.Errorf("apdl: @symbol() is required")
	}
	if !validSymbols[cp.Symbol] {
		return nil, fmt.Errorf("apdl: unknown symbol %q — valid: Eban, Nkyinkyim, Dwennimmen, Fawohodie", cp.Symbol)
	}

	// ── 3. EXTRACT CONTROL BLOCK ──────────────────────────────────────────────
	if err := extractControlBlock(source, cp); err != nil {
		return nil, fmt.Errorf("apdl: control block parse error: %w", err)
	}

	if cp.ControlID == "" {
		return nil, fmt.Errorf("apdl: no 'control <ID> { ... }' block found")
	}

	// ── 4. GENERATE COMMANDS ──────────────────────────────────────────────────
	cp.Commands = generateCommands(cp)

	// ── 5. GENERATE ANSIBLE YAML ──────────────────────────────────────────────
	cp.AnsibleYAML = generateAnsibleYAML(cp)

	// ── 6. SOURCE HASH ────────────────────────────────────────────────────────
	h := sha256.Sum256([]byte(source))
	cp.SourceHash = hex.EncodeToString(h[:])

	// ── 7. ML-DSA-65 SIGNATURE ───────────────────────────────────────────────
	if privKey != nil {
		canonical, err := canonicalBundleBytes(cp)
		if err != nil {
			return nil, fmt.Errorf("apdl: cannot canonicalize bundle for signing: %w", err)
		}
		sig, err := adinkra.Sign(privKey, canonical)
		if err != nil {
			return nil, fmt.Errorf("apdl: ML-DSA-65 signing failed: %w", err)
		}
		cp.Signature = sig
	}

	return cp, nil
}

// Verify checks a CompiledPolicy's ML-DSA-65 signature against the agent public key.
func Verify(cp *CompiledPolicy, pubKey []byte) (bool, error) {
	if len(cp.Signature) == 0 {
		return false, fmt.Errorf("apdl: bundle is unsigned")
	}
	canonical, err := canonicalBundleBytes(cp)
	if err != nil {
		return false, fmt.Errorf("apdl: canonicalize for verify: %w", err)
	}
	return adinkra.Verify(pubKey, canonical, cp.Signature)
}

// ── Parsing helpers ───────────────────────────────────────────────────────────

var (
	reSymbol    = regexp.MustCompile(`@symbol\(\s*([\w]+)\s*\)`)
	reFramework = regexp.MustCompile(`@framework\(\s*([\w.\-]+)\s*\)`)
	reTier      = regexp.MustCompile(`@tier\(\s*([\w]+)\s*\)`)
	reGate      = regexp.MustCompile(`@gate\(\s*([\w]+)\s*\)`)
	reControl   = regexp.MustCompile(`control\s+([\w\-\.]+)\s*\{`)
	reMaps      = regexp.MustCompile(`maps\s*:\s*(.+)`)
)

func extractDirectives(source string, cp *CompiledPolicy) error {
	if m := reSymbol.FindStringSubmatch(source); len(m) > 1 {
		cp.Symbol = strings.TrimSpace(m[1])
	}
	if m := reFramework.FindStringSubmatch(source); len(m) > 1 {
		cp.Framework = strings.TrimSpace(m[1])
	}
	if m := reTier.FindStringSubmatch(source); len(m) > 1 {
		cp.Tier = strings.TrimSpace(m[1])
	}
	if m := reGate.FindStringSubmatch(source); len(m) > 1 {
		cp.Gate = strings.TrimSpace(m[1])
	}
	return nil
}

func extractControlBlock(source string, cp *CompiledPolicy) error {
	// Extract control ID
	if m := reControl.FindStringSubmatch(source); len(m) > 1 {
		cp.ControlID = strings.TrimSpace(m[1])
	}

	// Find the block content between { }
	start := strings.Index(source, "{")
	end := strings.LastIndex(source, "}")
	if start == -1 || end == -1 || end <= start {
		return nil // no block — not an error if control ID also absent
	}
	block := source[start+1 : end]

	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}

		// maps: directive
		if m := reMaps.FindStringSubmatch(line); len(m) > 1 {
			for _, mapping := range strings.Split(m[1], ",") {
				cp.Mappings = append(cp.Mappings, strings.TrimSpace(mapping))
			}
			continue
		}

		// key = value or key: value directives
		if strings.Contains(line, "=") {
			parts := strings.SplitN(line, "=", 2)
			cp.Requirements[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
		} else if strings.Contains(line, ":") && !strings.HasPrefix(line, "maps") {
			parts := strings.SplitN(line, ":", 2)
			cp.Requirements[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
		}
	}
	return nil
}

// generateCommands translates parsed requirements into daemon-executable commands.
// This is the "compiler backend" — it maps APDL requirements to OS commands.
func generateCommands(cp *CompiledPolicy) [][]string {
	var cmds [][]string

	// require: pam_faillock → authselect select sssd with-faillock
	if req, ok := cp.Requirements["require"]; ok {
		switch req {
		case "pam_faillock":
			cmds = append(cmds, []string{"authselect", "select", "sssd", "with-faillock"})
			if deny, ok := cp.Requirements["deny"]; ok {
				cmds = append(cmds, []string{"faillock", "--conf", "/etc/security/faillock.conf",
					"--option", "deny=" + deny})
			}
			if unlock, ok := cp.Requirements["unlock_time"]; ok {
				cmds = append(cmds, []string{"faillock", "--conf", "/etc/security/faillock.conf",
					"--option", "unlock_time=" + unlock})
			}
		case "fips_mode":
			cmds = append(cmds, []string{"sysctl", "-w", "crypto.fips_enabled=1"})
			cmds = append(cmds, []string{"dracut", "-f", "--regenerate-all"})
		case "aslr":
			cmds = append(cmds, []string{"sysctl", "-w", "kernel.randomize_va_space=2"})
		case "auditd":
			cmds = append(cmds, []string{"systemctl", "enable", "--now", "auditd"})
		}
	}

	return cmds
}

// generateAnsibleYAML produces an Ansible playbook YAML from the compiled policy.
func generateAnsibleYAML(cp *CompiledPolicy) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# Generated by ASAF APDL Compiler — %s\n", cp.CompiledAt))
	b.WriteString(fmt.Sprintf("# Control: %s | Framework: %s | Symbol: %s\n\n", cp.ControlID, cp.Framework, cp.Symbol))
	b.WriteString("---\n- name: ASAF Remediation\n  hosts: localhost\n  become: yes\n  tasks:\n")

	for i, cmd := range cp.Commands {
		taskName := fmt.Sprintf("ASAF_%s_task_%d", cp.ControlID, i+1)
		b.WriteString(fmt.Sprintf("  - name: %s\n", taskName))
		if len(cmd) >= 2 && cmd[0] == "systemctl" {
			b.WriteString(fmt.Sprintf("    service:\n      name: %s\n      state: started\n      enabled: yes\n", cmd[len(cmd)-1]))
		} else {
			b.WriteString(fmt.Sprintf("    command: %s\n", strings.Join(cmd, " ")))
		}
	}

	return b.String()
}

// canonicalBundleBytes produces deterministic bytes for signing/verification.
// The Signature field is zeroed before marshaling.
func canonicalBundleBytes(cp *CompiledPolicy) ([]byte, error) {
	c := *cp
	c.Signature = nil
	return json.Marshal(c)
}
