// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjknkjbrjgljuovaazeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqa25ramJyamdsanVvdmFhemV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTMzNDksImV4cCI6MjA3MTQyOTM0OX0.ioWr3_viAbWJHAaHnBxQrzSXtgUlcAAjrPWEsoSh6sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: (globalThis as { localStorage?: Storage }).localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE exchanges a short-lived code instead of embedding the access token in the
    // URL hash fragment (implicit flow), preventing token leakage via browser history
    // and referrer headers.  The client auto-exchanges the ?code= param on redirect.
    flowType: 'pkce',
    detectSessionInUrl: true,
  }
});